"""한약재 확장 시드 데이터 적재 스크립트.

기존 86종을 보완하여 ~170종의 신규 한약재를 추가한다 (목표 총 250+종).
대한약전 및 중국약전(中國藥典), 본초학(本草學) 분류 기반.

카테고리 확장:
  발한약, 청열약, 사하약, 거풍습약, 방향화습약, 이수삼습약,
  온리약, 이기약, 소식약, 구충약, 지해평천약, 평간식풍약,
  개규약, 보음약, 보양약, 수삽약, 외용약, 보기약, 보혈약,
  활혈거어약 등

사용법:
    python scripts/data-import/seed_herbal_medicines_expanded.py
    python scripts/data-import/seed_herbal_medicines_expanded.py --dry-run
"""

import asyncio
import json
import logging
import sys
import time
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sqlalchemy import text

from src.backend.core.database import async_session_factory

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)-7s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("seed_herbal_medicines_expanded")


# ============================================================
# 한약재 확장 시드 데이터 (~170종 신규)
# ============================================================

HERBAL_MEDICINES_EXPANDED: list[dict[str, Any]] = [
    # ================================================================
    # 1. 발한약(發汗藥) — +8
    # ================================================================
    {
        "name": "세신",
        "slug": "herbal-asarum",
        "korean_name": "세신",
        "latin_name": "Asarum sieboldii Miq.",
        "category": "발한약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐", "신", "심"]},
        "description": "거풍산한, 통규지통, 온폐화음에 사용하는 약재. 뿌리가 가늘어 세신이라 함",
        "efficacy": "거풍산한, 통규지통, 온폐화음",
        "precautions": "아리스톨로키아산 함유 가능(산지 확인 필수). 기허다한, 혈허두통 환자 금기. 여로(藜蘆)와 배합 금기.",
    },
    {
        "name": "창이자",
        "slug": "herbal-xanthium",
        "korean_name": "창이자",
        "latin_name": "Xanthium strumarium L.",
        "category": "발한약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["폐"]},
        "description": "산풍거습, 통비규에 사용하는 약재. 도꼬마리 열매",
        "efficacy": "산풍습, 통비규, 지통",
        "precautions": "독성 있음(카르복시아트락틸로사이드). 과량 복용 시 간독성, 신독성. 혈허두통에는 부적합.",
    },
    {
        "name": "신이",
        "slug": "herbal-magnolia-flower",
        "korean_name": "신이",
        "latin_name": "Magnolia biondii Pamp.",
        "category": "발한약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐", "위"]},
        "description": "발산풍한, 통비규에 사용하는 약재. 목련 꽃봉오리",
        "efficacy": "발산풍한, 통비규",
        "precautions": "음허화왕 환자 주의. 비점막 자극 가능.",
    },
    {
        "name": "국화",
        "slug": "herbal-chrysanthemum",
        "korean_name": "국화",
        "latin_name": "Chrysanthemum morifolium Ramat.",
        "category": "발한약",
        "properties": {"taste": "감미, 고미", "nature": "미한", "meridian": ["폐", "간"]},
        "description": "소산풍열, 평간명목, 청열해독에 사용하는 약재",
        "efficacy": "소산풍열, 평간명목, 청열해독",
        "precautions": "기허위한, 설사 환자 주의. 국화과 알레르기 환자 금기.",
    },
    {
        "name": "상엽",
        "slug": "herbal-mulberry-leaf",
        "korean_name": "상엽",
        "latin_name": "Morus alba L.",
        "category": "발한약",
        "properties": {"taste": "감미, 고미", "nature": "한", "meridian": ["폐", "간"]},
        "description": "소산풍열, 청폐윤조, 청간명목에 사용. 뽕나무 잎",
        "efficacy": "소산풍열, 청폐윤조, 청간명목",
        "precautions": "혈당강하 작용. 당뇨약 병용 시 저혈당 주의.",
    },
    {
        "name": "우방자",
        "slug": "herbal-arctium",
        "korean_name": "우방자",
        "latin_name": "Arctium lappa L.",
        "category": "발한약",
        "properties": {"taste": "신미, 고미", "nature": "한", "meridian": ["폐", "위"]},
        "description": "소산풍열, 선폐투진, 해독이인후에 사용. 우엉 씨",
        "efficacy": "소산풍열, 선폐투진, 해독이인후",
        "precautions": "기허설사 환자 금기. 혈당강하 작용 보고.",
    },
    {
        "name": "승마",
        "slug": "herbal-cimicifuga",
        "korean_name": "승마",
        "latin_name": "Cimicifuga heracleifolia Kom.",
        "category": "발한약",
        "properties": {"taste": "신미, 감미", "nature": "미한", "meridian": ["폐", "비", "대장", "위"]},
        "description": "발표투진, 청열해독, 승양거함에 사용하는 약재",
        "efficacy": "발표투진, 청열해독, 승양거함",
        "precautions": "간독성 보고(Actaea racemosa 계열). 마진(痲疹) 이미 투발한 경우 사용 금지. 음허화왕 환자 주의.",
    },
    {
        "name": "만형자",
        "slug": "herbal-vitex",
        "korean_name": "만형자",
        "latin_name": "Vitex trifolia L.",
        "category": "발한약",
        "properties": {"taste": "신미, 고미", "nature": "미한", "meridian": ["방광", "간", "위"]},
        "description": "소산풍열, 청리두목에 사용하는 약재",
        "efficacy": "소산풍열, 청리두목",
        "precautions": "위허(胃虛) 환자, 혈허두통에는 부적합.",
    },

    # ================================================================
    # 2. 청열약(淸熱藥) — +10 (석고, 노근, 하고초, 어성초, 패장초, 목단피, 자초, 백두옹, 관중, 결명자)
    #    지모·포공영은 기존 데이터에 존재
    # ================================================================
    {
        "name": "석고",
        "slug": "herbal-gypsum",
        "korean_name": "석고",
        "latin_name": "CaSO4·2H2O (Gypsum Fibrosum)",
        "category": "청열약",
        "properties": {"taste": "감미, 신미", "nature": "대한", "meridian": ["폐", "위"]},
        "description": "청열사화, 제번지갈에 사용하는 광물성 약재. 백호탕의 주약",
        "efficacy": "청열사화, 제번지갈",
        "precautions": "비위 허한, 양허(陽虛) 환자 금기. 광물성이므로 장기 복용 주의.",
    },
    {
        "name": "노근",
        "slug": "herbal-phragmites",
        "korean_name": "노근",
        "latin_name": "Phragmites communis Trin.",
        "category": "청열약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["폐", "위"]},
        "description": "청열생진, 제번지구에 사용하는 약재. 갈대 뿌리",
        "efficacy": "청열생진, 제번지구, 이뇨",
        "precautions": "비위 허한 환자 주의. 특별한 약물 상호작용 보고 적음.",
    },
    {
        "name": "하고초",
        "slug": "herbal-prunella",
        "korean_name": "하고초",
        "latin_name": "Prunella vulgaris L.",
        "category": "청열약",
        "properties": {"taste": "고미, 신미", "nature": "한", "meridian": ["간", "담"]},
        "description": "청간사화, 산결소종에 사용. 꿀풀과 식물의 과수(花穗)",
        "efficacy": "청간사화, 명목, 산결소종",
        "precautions": "비위 허약 환자 주의. 항고혈압 작용으로 혈압약 병용 시 저혈압 가능.",
    },
    {
        "name": "어성초",
        "slug": "herbal-houttuynia",
        "korean_name": "어성초",
        "latin_name": "Houttuynia cordata Thunb.",
        "category": "청열약",
        "properties": {"taste": "신미", "nature": "미한", "meridian": ["폐"]},
        "description": "청열해독, 소옹배농, 이뇨통림에 사용. 삼백초과 약초",
        "efficacy": "청열해독, 소옹배농, 이뇨통림",
        "precautions": "허한(虛寒) 체질 환자 주의. 알레르기 반응 보고.",
    },
    {
        "name": "패장초",
        "slug": "herbal-patrinia",
        "korean_name": "패장초",
        "latin_name": "Patrinia scabiosifolia Fisch.",
        "category": "청열약",
        "properties": {"taste": "신미, 고미", "nature": "미한", "meridian": ["위", "대장", "간"]},
        "description": "청열해독, 소옹배농, 거어지통에 사용하는 약재",
        "efficacy": "청열해독, 소옹배농, 거어지통",
        "precautions": "비위 허한 환자 과량 복용 주의. 임산부 주의.",
    },
    {
        "name": "목단피",
        "slug": "herbal-moutan",
        "korean_name": "목단피",
        "latin_name": "Paeonia suffruticosa Andr.",
        "category": "청열약",
        "properties": {"taste": "고미, 신미", "nature": "미한", "meridian": ["심", "간", "신"]},
        "description": "청열양혈, 활혈거어에 사용. 모란 뿌리 껍질",
        "efficacy": "청열양혈, 활혈화어, 퇴허열",
        "precautions": "임산부 금기. 월경과다 환자 주의. 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "자초",
        "slug": "herbal-lithospermum",
        "korean_name": "자초",
        "latin_name": "Lithospermum erythrorhizon Sieb. et Zucc.",
        "category": "청열약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["심", "간"]},
        "description": "양혈활혈, 해독투진에 사용. 지치과 식물의 뿌리",
        "efficacy": "양혈활혈, 해독투진, 이뇨통림",
        "precautions": "비위 허약, 설사 환자 주의. 시코닌 성분이 간독성 유발 가능.",
    },
    {
        "name": "백두옹",
        "slug": "herbal-pulsatilla",
        "korean_name": "백두옹",
        "latin_name": "Pulsatilla koreana (Yabe ex Nakai) Nakai ex Mori",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["위", "대장"]},
        "description": "청열해독, 양혈지리에 사용하는 약재. 열독이질(痢)의 요약",
        "efficacy": "청열해독, 양혈지리",
        "precautions": "허한성 설사 환자 금기. 독성 있어 용량 엄수.",
    },
    {
        "name": "관중",
        "slug": "herbal-dryopteris",
        "korean_name": "관중",
        "latin_name": "Dryopteris crassirhizoma Nakai",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["간", "위"]},
        "description": "청열해독, 구충, 지혈에 사용하는 양치류 약재",
        "efficacy": "청열해독, 구충, 지혈",
        "precautions": "간독성, 신독성 보고. 임산부 금기. 간질환 환자 금기. 과량 시 시력장애.",
    },
    {
        "name": "결명자",
        "slug": "herbal-cassia-seed",
        "korean_name": "결명자",
        "latin_name": "Cassia obtusifolia L.",
        "category": "청열약",
        "properties": {"taste": "감미, 고미, 함미", "nature": "미한", "meridian": ["간", "신", "대장"]},
        "description": "청간명목, 윤장통변에 사용. 결명차의 원료",
        "efficacy": "청간명목, 이수통변",
        "precautions": "비위 허한, 설사 환자 주의. 혈압강하 작용으로 혈압약 병용 시 저혈압 가능.",
    },

    # ================================================================
    # 3. 사하약(瀉下藥) — +6
    # ================================================================
    {
        "name": "망초",
        "slug": "herbal-mirabilite",
        "korean_name": "망초",
        "latin_name": "Na2SO4·10H2O (Natrii Sulfas)",
        "category": "사하약",
        "properties": {"taste": "고미, 함미", "nature": "한", "meridian": ["위", "대장"]},
        "description": "사하통변, 윤조연견, 청화열에 사용하는 광물성 약재",
        "efficacy": "사하통변, 윤조연견, 청화열",
        "precautions": "임산부 금기. 비위 허약, 설사 환자 금기. 전해질 불균형 유발 가능.",
    },
    {
        "name": "노회",
        "slug": "herbal-aloe",
        "korean_name": "노회",
        "latin_name": "Aloe vera (L.) Burm.f.",
        "category": "사하약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["간", "위", "대장"]},
        "description": "사하통변, 청간사화, 구충에 사용. 알로에",
        "efficacy": "사하, 청간, 살충",
        "precautions": "임산부 금기(자궁수축 유발). 수유부 주의. 안트라퀴논 성분으로 장기 복용 시 대장흑피증.",
    },
    {
        "name": "번사엽",
        "slug": "herbal-senna",
        "korean_name": "번사엽",
        "latin_name": "Cassia angustifolia Vahl",
        "category": "사하약",
        "properties": {"taste": "감미, 고미", "nature": "한", "meridian": ["대장"]},
        "description": "사열통변, 행수소장에 사용. 센나 잎",
        "efficacy": "사열통변, 행수소장",
        "precautions": "임산부 금기. 센노사이드 함유. 장기 복용 시 전해질 불균형, 대장멜라닌증. 강심배당체와 병용 시 저칼륨혈증 주의.",
    },
    {
        "name": "우복자",
        "slug": "herbal-raphanus-seed",
        "korean_name": "우복자",
        "latin_name": "Raphanus sativus L.",
        "category": "사하약",
        "properties": {"taste": "신미, 감미", "nature": "평", "meridian": ["폐", "비", "위"]},
        "description": "소식제창, 강기화담에 사용. 무 씨",
        "efficacy": "소식도체, 강기화담",
        "precautions": "기허(氣虛) 환자 주의. 인삼과 함께 복용하면 인삼의 보기 효능을 감소시킬 수 있음.",
    },
    {
        "name": "화마인",
        "slug": "herbal-cannabis-seed",
        "korean_name": "화마인",
        "latin_name": "Cannabis sativa L.",
        "category": "사하약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["비", "위", "대장"]},
        "description": "윤장통변에 사용하는 약재. 대마 씨(THC 미함유 종자)",
        "efficacy": "윤장통변, 자양보허",
        "precautions": "설사 환자 금기. 법적 규제 확인 필수(종자 외 부위 사용 불가).",
    },
    {
        "name": "육리인",
        "slug": "herbal-prunus-japonica-seed",
        "korean_name": "육리인",
        "latin_name": "Prunus japonica Thunb.",
        "category": "사하약",
        "properties": {"taste": "신미, 고미, 감미", "nature": "평", "meridian": ["비", "대장", "소장"]},
        "description": "윤장통변, 하기이수에 사용. 이스라지나무 종자",
        "efficacy": "윤장통변, 하기이수",
        "precautions": "임산부 주의. 아미그달린 미량 함유.",
    },

    # ================================================================
    # 4. 거풍습약(祛風濕藥) — +7 (두충은 기존 존재)
    # ================================================================
    {
        "name": "상기생",
        "slug": "herbal-loranthus",
        "korean_name": "상기생",
        "latin_name": "Loranthus parasiticus (L.) Merr.",
        "category": "거풍습약",
        "properties": {"taste": "고미, 감미", "nature": "평", "meridian": ["간", "신"]},
        "description": "거풍습, 보간신, 강근골, 안태에 사용. 뽕나무 겨우살이",
        "efficacy": "거풍습, 보간신, 강근골, 안태",
        "precautions": "특별한 금기 보고 적음. 혈압강하 작용으로 혈압약 병용 시 주의.",
    },
    {
        "name": "우슬",
        "slug": "herbal-achyranthes",
        "korean_name": "우슬",
        "latin_name": "Achyranthes bidentata Blume",
        "category": "거풍습약",
        "properties": {"taste": "고미, 산미", "nature": "평", "meridian": ["간", "신"]},
        "description": "활혈거어, 보간신, 강근골, 이뇨통림, 인혈하행에 사용. 쇠무릎",
        "efficacy": "활혈거어, 보간신, 강근골, 이뇨통림, 인혈하행",
        "precautions": "임산부 금기(활혈하행 작용). 월경과다 환자 주의. 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "백선피",
        "slug": "herbal-dictamnus",
        "korean_name": "백선피",
        "latin_name": "Dictamnus dasycarpus Turcz.",
        "category": "거풍습약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["비", "위"]},
        "description": "청열조습, 거풍해독에 사용. 피부 질환에 다용",
        "efficacy": "청열조습, 거풍해독",
        "precautions": "비위 허한 환자 주의. 간독성 보고 사례 있음.",
    },
    {
        "name": "진교",
        "slug": "herbal-gentiana-macrophylla",
        "korean_name": "진교",
        "latin_name": "Gentiana macrophylla Pall.",
        "category": "거풍습약",
        "properties": {"taste": "고미, 신미", "nature": "미한", "meridian": ["위", "간", "담"]},
        "description": "거풍습, 서근활락, 퇴허열, 청습열에 사용",
        "efficacy": "거풍습, 서근활락, 퇴허열, 청습열",
        "precautions": "비위 허한, 설사 환자 주의. 대변 연화 가능.",
    },
    {
        "name": "방기",
        "slug": "herbal-stephania",
        "korean_name": "방기",
        "latin_name": "Sinomenium acutum (Thunb.) Rehder & E.H.Wilson",
        "category": "거풍습약",
        "properties": {"taste": "고미, 신미", "nature": "한", "meridian": ["방광", "폐"]},
        "description": "거풍습, 지통, 이수에 사용하는 약재",
        "efficacy": "거풍습, 지통, 이수소종",
        "precautions": "비위 허약 환자 주의. 아리스톨로키아산 함유종(광방기)과 혼용 금기 — 신독성.",
    },
    {
        "name": "해풍등",
        "slug": "herbal-piper-kadsura",
        "korean_name": "해풍등",
        "latin_name": "Piper kadsura (Choisy) Ohwi",
        "category": "거풍습약",
        "properties": {"taste": "신미, 고미", "nature": "미온", "meridian": ["간"]},
        "description": "거풍습, 통경락, 지비통에 사용하는 등본(藤本) 약재",
        "efficacy": "거풍습, 통경락, 지비통",
        "precautions": "음허혈조(陰虛血燥) 환자 주의.",
    },
    {
        "name": "낙석등",
        "slug": "herbal-trachelospermum",
        "korean_name": "낙석등",
        "latin_name": "Trachelospermum jasminoides (Lindl.) Lem.",
        "category": "거풍습약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["심", "간"]},
        "description": "거풍통락, 양혈소종에 사용. 마삭줄",
        "efficacy": "거풍통락, 양혈소종",
        "precautions": "독성 미약하나 과량 시 구토 가능. 임산부 주의.",
    },

    # ================================================================
    # 5. 방향화습약(芳香化濕藥) — +4 (사인·초과는 기존 존재)
    # ================================================================
    {
        "name": "곽향",
        "slug": "herbal-agastache",
        "korean_name": "곽향",
        "latin_name": "Agastache rugosa (Fisch. & C.A.Mey.) Kuntze",
        "category": "방향화습약",
        "properties": {"taste": "신미", "nature": "미온", "meridian": ["비", "위", "폐"]},
        "description": "방향화습, 화중지구, 발표해서에 사용. 곽향정기산의 주약",
        "efficacy": "방향화탁, 화중지구, 발표해서",
        "precautions": "음허화왕 환자 주의. 특별한 약물 상호작용 보고 적음.",
    },
    {
        "name": "창출",
        "slug": "herbal-atractylodes-rhizome",
        "korean_name": "창출",
        "latin_name": "Atractylodes lancea (Thunb.) DC.",
        "category": "방향화습약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["비", "위"]},
        "description": "조습건비, 거풍산한에 사용. 백출(白朮)과 구별",
        "efficacy": "조습건비, 거풍산한, 명목",
        "precautions": "음허내열, 기허다한 환자 주의.",
    },
    {
        "name": "후박",
        "slug": "herbal-magnolia-bark",
        "korean_name": "후박",
        "latin_name": "Magnolia officinalis Rehder & E.H.Wilson",
        "category": "방향화습약",
        "properties": {"taste": "고미, 신미", "nature": "온", "meridian": ["비", "위", "폐", "대장"]},
        "description": "조습소담, 하기제만에 사용. 목련과 나무 껍질",
        "efficacy": "조습소담, 하기제만",
        "precautions": "임산부 주의. 기허, 진액부족 환자 주의.",
    },
    {
        "name": "백두구",
        "slug": "herbal-cardamom-round",
        "korean_name": "백두구",
        "latin_name": "Amomum kravanh Pierre ex Gagnep.",
        "category": "방향화습약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐", "비", "위"]},
        "description": "화습행기, 온중지구에 사용. 둥근 두구(豆蔲)",
        "efficacy": "화습행기, 온중지구",
        "precautions": "음허혈조, 진액부족 환자 주의. 오래 달이면 약효 감소(후하).",
    },

    # ================================================================
    # 6. 이수삼습약(利水滲濕藥) — +8
    # ================================================================
    {
        "name": "저령",
        "slug": "herbal-polyporus",
        "korean_name": "저령",
        "latin_name": "Polyporus umbellatus (Pers.) Fr.",
        "category": "이수삼습약",
        "properties": {"taste": "감미, 담미", "nature": "평", "meridian": ["신", "방광"]},
        "description": "이수삼습에 사용하는 약재. 버섯류(균핵)",
        "efficacy": "이수삼습",
        "precautions": "무습(無濕) 환자는 주의. 이뇨제와 병용 시 과도한 이뇨 가능.",
    },
    {
        "name": "활석",
        "slug": "herbal-talcum",
        "korean_name": "활석",
        "latin_name": "Mg3(Si4O10)(OH)2 (Talcum)",
        "category": "이수삼습약",
        "properties": {"taste": "감미, 담미", "nature": "한", "meridian": ["방광", "위"]},
        "description": "이뇨통림, 청해서열에 사용하는 광물성 약재",
        "efficacy": "이뇨통림, 청해서열",
        "precautions": "비위 허한 환자 주의. 정활(精滑) 환자 금기. 장기 복용 시 전해질 불균형.",
    },
    {
        "name": "통초",
        "slug": "herbal-tetrapanax",
        "korean_name": "통초",
        "latin_name": "Tetrapanax papyrifer (Hook.) K.Koch",
        "category": "이수삼습약",
        "properties": {"taste": "감미, 담미", "nature": "미한", "meridian": ["폐", "위"]},
        "description": "이뇨통림, 통기하유에 사용. 통탈목의 줄기 속",
        "efficacy": "이뇨통림, 통기하유",
        "precautions": "임산부 주의. 이뇨제와 병용 시 전해질 불균형 가능.",
    },
    {
        "name": "편축",
        "slug": "herbal-polygonum-aviculare",
        "korean_name": "편축",
        "latin_name": "Polygonum aviculare L.",
        "category": "이수삼습약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["방광"]},
        "description": "이뇨통림, 살충지양에 사용하는 약재. 마디풀",
        "efficacy": "이뇨통림, 살충지양",
        "precautions": "특별한 금기 보고 적음. 이뇨제와 병용 시 주의.",
    },
    {
        "name": "구맥",
        "slug": "herbal-dianthus",
        "korean_name": "구맥",
        "latin_name": "Dianthus superbus L.",
        "category": "이수삼습약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["심", "소장"]},
        "description": "이뇨통림, 활혈통경에 사용. 패랭이꽃",
        "efficacy": "이뇨통림, 활혈통경",
        "precautions": "임산부 금기(통경 작용). 비위 허약 환자 주의.",
    },
    {
        "name": "해금사",
        "slug": "herbal-lygodium",
        "korean_name": "해금사",
        "latin_name": "Lygodium japonicum (Thunb.) Sw.",
        "category": "이수삼습약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["방광", "소장"]},
        "description": "이뇨통림, 청열해독에 사용. 실고사리 포자",
        "efficacy": "이뇨통림, 청열해독",
        "precautions": "신양허 환자 주의.",
    },
    {
        "name": "석위",
        "slug": "herbal-pyrrosia",
        "korean_name": "석위",
        "latin_name": "Pyrrosia lingua (Thunb.) Farw.",
        "category": "이수삼습약",
        "properties": {"taste": "감미, 고미", "nature": "미한", "meridian": ["폐", "방광"]},
        "description": "이뇨통림, 청폐지해에 사용하는 양치류 약재",
        "efficacy": "이뇨통림, 청폐지해, 양혈지혈",
        "precautions": "음허(陰虛) 무습열 환자 주의.",
    },
    {
        "name": "비해",
        "slug": "herbal-dioscorea-tokoro",
        "korean_name": "비해",
        "latin_name": "Dioscorea tokoro Makino ex Miyabe",
        "category": "이수삼습약",
        "properties": {"taste": "고미", "nature": "평", "meridian": ["신", "위"]},
        "description": "이습거탁, 거풍제비에 사용하는 약재",
        "efficacy": "이습거탁, 거풍제비",
        "precautions": "신허음휴(腎虛陰虧) 환자 주의.",
    },

    # ================================================================
    # 7. 온리약(溫裏藥) — +5
    # ================================================================
    {
        "name": "정향",
        "slug": "herbal-clove",
        "korean_name": "정향",
        "latin_name": "Syzygium aromaticum (L.) Merr. & L.M.Perry",
        "category": "온리약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["비", "위", "폐", "신"]},
        "description": "온중강역, 보신조양에 사용. 정향나무 꽃봉오리",
        "efficacy": "온중강역, 보신조양",
        "precautions": "열증, 음허화왕 환자 금기. 유게놀(eugenol) 함유로 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "소회향",
        "slug": "herbal-fennel",
        "korean_name": "소회향",
        "latin_name": "Foeniculum vulgare Mill.",
        "category": "온리약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["간", "신", "비", "위"]},
        "description": "산한지통, 이기화위에 사용. 회향(茴香) 열매",
        "efficacy": "산한지통, 이기화위",
        "precautions": "음허화왕 환자 주의. 에스트로겐 유사 작용으로 호르몬 관련 약물 주의.",
    },
    {
        "name": "고량강",
        "slug": "herbal-galangal",
        "korean_name": "고량강",
        "latin_name": "Alpinia officinarum Hance",
        "category": "온리약",
        "properties": {"taste": "신미", "nature": "열", "meridian": ["비", "위"]},
        "description": "온위지구, 산한지통에 사용. 양강(良薑)이라고도 함",
        "efficacy": "온위산한, 소식지통",
        "precautions": "음허유열(陰虛有熱), 위화치통(胃火齒痛) 환자 금기.",
    },
    {
        "name": "화초",
        "slug": "herbal-zanthoxylum",
        "korean_name": "화초",
        "latin_name": "Zanthoxylum bungeanum Maxim.",
        "category": "온리약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["비", "위", "신"]},
        "description": "온중지통, 살충지양에 사용. 산초(초피) 열매",
        "efficacy": "온중산한, 제습지통, 살충",
        "precautions": "음허화왕 환자 금기. 임산부 주의. 국소마취 작용.",
    },
    {
        "name": "필발",
        "slug": "herbal-piper-longum",
        "korean_name": "필발",
        "latin_name": "Piper longum L.",
        "category": "온리약",
        "properties": {"taste": "신미", "nature": "열", "meridian": ["위", "대장"]},
        "description": "온중산한, 하기지통에 사용. 긴후추",
        "efficacy": "온중산한, 하기지통",
        "precautions": "실열(實熱) 환자 금기. 피페린(piperine) 함유로 CYP3A4, P-gp에 영향 — 다수 약물의 생체이용률 변경 가능.",
    },

    # ================================================================
    # 8. 이기약(理氣藥) — +6 (후박·오약은 기존 존재)
    # ================================================================
    {
        "name": "지각",
        "slug": "herbal-aurantium-mature",
        "korean_name": "지각",
        "latin_name": "Citrus aurantium L.",
        "category": "이기약",
        "properties": {"taste": "고미, 신미, 산미", "nature": "미한", "meridian": ["비", "위"]},
        "description": "이기관중, 행체소비에 사용. 탱자나무의 성숙 과실",
        "efficacy": "이기관중, 행체소비",
        "precautions": "비위 허약 환자 주의. 시네프린 함유로 교감신경흥분제, MAO 억제제 병용 금기.",
    },
    {
        "name": "지실",
        "slug": "herbal-aurantium-immature",
        "korean_name": "지실",
        "latin_name": "Citrus aurantium L. (미숙과)",
        "category": "이기약",
        "properties": {"taste": "고미, 신미, 산미", "nature": "미한", "meridian": ["비", "위"]},
        "description": "파기소적, 화담산비에 사용. 탱자나무 미숙 과실(지각보다 작용 강함)",
        "efficacy": "파기소적, 화담산비",
        "precautions": "임산부 금기. 비위 허약 환자 주의. 시네프린 함유.",
    },
    {
        "name": "청피",
        "slug": "herbal-citrus-green",
        "korean_name": "청피",
        "latin_name": "Citrus reticulata Blanco (미숙과)",
        "category": "이기약",
        "properties": {"taste": "고미, 신미", "nature": "온", "meridian": ["간", "담", "위"]},
        "description": "소간파기, 소적화체에 사용. 귤의 미숙 과피(진피보다 작용 강함)",
        "efficacy": "소간파기, 소적화체",
        "precautions": "기허(氣虛) 환자 주의. 과량 시 진기(眞氣) 손상 가능.",
    },
    {
        "name": "천련자",
        "slug": "herbal-melia",
        "korean_name": "천련자",
        "latin_name": "Melia toosendan Sieb. et Zucc.",
        "category": "이기약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["간", "소장", "방광"]},
        "description": "소간사열, 행기지통, 살충에 사용. 금릉자(金鈴子)라고도 함",
        "efficacy": "소간사열, 행기지통, 살충",
        "precautions": "비위 허한 환자 금기. 간독성 보고. 과량 시 중독 위험(구토, 설사, 호흡억제).",
    },
    {
        "name": "불수",
        "slug": "herbal-citrus-medica",
        "korean_name": "불수",
        "latin_name": "Citrus medica L. var. sarcodactylis Swingle",
        "category": "이기약",
        "properties": {"taste": "신미, 고미, 산미", "nature": "온", "meridian": ["간", "비", "폐"]},
        "description": "소간이기, 화위지통에 사용. 불수감(佛手柑)",
        "efficacy": "소간이기, 화위지통, 조습화담",
        "precautions": "음허화왕 환자 주의. 특별한 약물 상호작용 보고 적음.",
    },
    {
        "name": "비파엽",
        "slug": "herbal-eriobotrya",
        "korean_name": "비파엽",
        "latin_name": "Eriobotrya japonica (Thunb.) Lindl.",
        "category": "이기약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["폐", "위"]},
        "description": "청폐지해, 강역지구에 사용. 비파나무 잎",
        "efficacy": "청폐지해, 강역지구",
        "precautions": "풍한(風寒) 해수에는 부적합. 사용 시 배면 솜털 제거 필수(인후 자극).",
    },

    # ================================================================
    # 9. 소식약(消食藥) — +5
    # ================================================================
    {
        "name": "산사",
        "slug": "herbal-crataegus",
        "korean_name": "산사",
        "latin_name": "Crataegus pinnatifida Bge.",
        "category": "소식약",
        "properties": {"taste": "산미, 감미", "nature": "미온", "meridian": ["비", "위", "간"]},
        "description": "소식화적, 활혈화어에 사용. 산사자(아가위) 열매",
        "efficacy": "소식화적, 활혈산어, 화담",
        "precautions": "비위 허약으로 적체(積滯) 없는 환자 주의. 항응고제 병용 시 출혈 위험. 위산과다 환자 과량 금기.",
    },
    {
        "name": "맥아",
        "slug": "herbal-malt",
        "korean_name": "맥아",
        "latin_name": "Hordeum vulgare L.",
        "category": "소식약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["비", "위"]},
        "description": "소식건위, 회유소장에 사용. 보리를 발아시킨 것",
        "efficacy": "행기소식, 건비개위, 퇴유소장",
        "precautions": "수유부 주의(유즙 분비 억제 가능). 글루텐 알레르기 환자 주의.",
    },
    {
        "name": "곡아",
        "slug": "herbal-rice-sprout",
        "korean_name": "곡아",
        "latin_name": "Oryza sativa L.",
        "category": "소식약",
        "properties": {"taste": "감미", "nature": "온", "meridian": ["비", "위"]},
        "description": "소식화적, 건비개위에 사용. 볍씨를 발아시킨 것",
        "efficacy": "소식화적, 건비개위",
        "precautions": "특별한 금기 보고 적음.",
    },
    {
        "name": "신곡",
        "slug": "herbal-massa-medicata",
        "korean_name": "신곡",
        "latin_name": "Massa Medicata Fermentata",
        "category": "소식약",
        "properties": {"taste": "감미, 신미", "nature": "온", "meridian": ["비", "위"]},
        "description": "소식화적, 건비화위에 사용. 약누룩(발효 제제)",
        "efficacy": "소식화적, 건비화위",
        "precautions": "특별한 금기 보고 적음. 발효 제제이므로 항생제 복용 중 효과 변동 가능.",
    },
    {
        "name": "계내금",
        "slug": "herbal-chicken-gizzard",
        "korean_name": "계내금",
        "latin_name": "Gallus gallus domesticus (내금)",
        "category": "소식약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["비", "위", "소장", "방광"]},
        "description": "소식건위, 삽정지유에 사용. 닭의 모이주머니 내벽",
        "efficacy": "건위소식, 삽정지유, 통림화석",
        "precautions": "비위 허한, 무적체(無積滯) 환자는 주의.",
    },

    # ================================================================
    # 10. 구충약(驅蟲藥) — +4 (관중은 청열약으로 위에서 추가)
    # ================================================================
    {
        "name": "사군자",
        "slug": "herbal-quisqualis",
        "korean_name": "사군자",
        "latin_name": "Quisqualis indica L.",
        "category": "구충약",
        "properties": {"taste": "감미", "nature": "온", "meridian": ["비", "위"]},
        "description": "살충소적, 건비에 사용. 회충(蛔蟲) 구충의 요약",
        "efficacy": "살충소적, 건비",
        "precautions": "과량 시 딸꾹질, 구토, 설사. 차(茶)와 함께 복용 금지(탄닌 결합 독성). 열성 자제(熱性 果仁)와 동복 주의.",
    },
    {
        "name": "빈랑자",
        "slug": "herbal-areca",
        "korean_name": "빈랑자",
        "latin_name": "Areca catechu L.",
        "category": "구충약",
        "properties": {"taste": "고미, 신미", "nature": "온", "meridian": ["위", "대장"]},
        "description": "살충소적, 강기행수, 제장절학에 사용. 빈랑나무 종자",
        "efficacy": "살충, 소적, 행기, 이수",
        "precautions": "아레콜린 함유(부교감신경 흥분). 기허하함(氣虛下陷) 환자 금기. 발암성 논란(구강암). 임산부 금기.",
    },
    {
        "name": "비자",
        "slug": "herbal-torreya",
        "korean_name": "비자",
        "latin_name": "Torreya nucifera (L.) Sieb. et Zucc.",
        "category": "구충약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["폐", "위", "대장"]},
        "description": "살충소적, 윤장통변에 사용. 비자나무 종자",
        "efficacy": "살충, 소적, 윤폐지해",
        "precautions": "설사 환자 주의. 과량 시 활장(滑腸) 가능.",
    },
    {
        "name": "뇌환",
        "slug": "herbal-omphalia",
        "korean_name": "뇌환",
        "latin_name": "Omphalia lapidescens Schroet.",
        "category": "구충약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["위", "대장"]},
        "description": "살충소적에 사용. 균핵(菌核) 약재",
        "efficacy": "살충소적",
        "precautions": "비위 허약 환자 주의. 독성 적으나 과량 시 위장 장애.",
    },

    # ================================================================
    # 11. 지해평천약(止咳平喘藥) — +6 (비파엽·상백피는 기존/위에 존재)
    # ================================================================
    {
        "name": "백부",
        "slug": "herbal-stemona",
        "korean_name": "백부",
        "latin_name": "Stemona japonica (Blume) Miq.",
        "category": "지해평천약",
        "properties": {"taste": "감미, 고미", "nature": "미온", "meridian": ["폐"]},
        "description": "윤폐지해, 살충에 사용하는 약재. 백부근(百部根)",
        "efficacy": "윤폐지해, 살충멸이",
        "precautions": "특별한 약물 상호작용 보고 적음. 과량 시 호흡억제 가능.",
    },
    {
        "name": "자완",
        "slug": "herbal-aster",
        "korean_name": "자완",
        "latin_name": "Aster tataricus L.f.",
        "category": "지해평천약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["폐"]},
        "description": "윤폐하기, 소담지해에 사용하는 약재",
        "efficacy": "윤폐하기, 소담지해",
        "precautions": "실열(實熱) 해수에는 부적합. 음허조해 단독 사용 주의.",
    },
    {
        "name": "관동화",
        "slug": "herbal-tussilago",
        "korean_name": "관동화",
        "latin_name": "Tussilago farfara L.",
        "category": "지해평천약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐"]},
        "description": "윤폐하기, 지해화담에 사용. 겨울에 꽃이 피어 관동(款冬)이라 함",
        "efficacy": "윤폐하기, 지해화담",
        "precautions": "피롤리지딘 알칼로이드(PA) 함유 가능 — 간독성. 장기 복용 주의. 임산부 금기.",
    },
    {
        "name": "마두령",
        "slug": "herbal-aristolochia-fruit",
        "korean_name": "마두령",
        "latin_name": "Aristolochia contorta Bge.",
        "category": "지해평천약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["폐", "대장"]},
        "description": "청폐강기, 지해평천에 사용하는 약재",
        "efficacy": "청폐강기, 지해평천",
        "precautions": "아리스톨로키아산 함유 — 신독성·발암성. 다수 국가에서 사용 제한. 대체 약재 사용 권장.",
    },
    {
        "name": "소자",
        "slug": "herbal-perilla-seed",
        "korean_name": "소자",
        "latin_name": "Perilla frutescens (L.) Britt. (종자)",
        "category": "지해평천약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐"]},
        "description": "강기화담, 지해평천, 윤장통변에 사용. 들깻잎 종자",
        "efficacy": "강기화담, 지해평천, 윤장통변",
        "precautions": "기허구해(氣虛久咳) 환자 주의. 활장(滑腸)하므로 설사 환자 주의.",
    },
    {
        "name": "백개자",
        "slug": "herbal-white-mustard",
        "korean_name": "백개자",
        "latin_name": "Sinapis alba L.",
        "category": "지해평천약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐"]},
        "description": "온폐화담, 이기산결에 사용. 흰겨자 종자",
        "efficacy": "온폐화담, 이기산결, 통락지통",
        "precautions": "폐허(肺虛) 해수, 음허화왕 환자 금기. 피부 자극성 강하여 외용 시 주의.",
    },

    # ================================================================
    # 12. 평간식풍약(平肝息風藥) — +6
    # ================================================================
    {
        "name": "영양각",
        "slug": "herbal-antelope-horn",
        "korean_name": "영양각",
        "latin_name": "Saiga tatarica L. (角)",
        "category": "평간식풍약",
        "properties": {"taste": "함미", "nature": "한", "meridian": ["간", "심"]},
        "description": "평간식풍, 청간명목, 양혈해독에 사용. CITES 규제 대상",
        "efficacy": "평간식풍, 청간명목, 산혈해독",
        "precautions": "CITES 부속서 II 등재 멸종위기종 — 사용 규제. 비위 허한 환자 주의. 대체재 사용 권장.",
    },
    {
        "name": "조구등",
        "slug": "herbal-uncaria",
        "korean_name": "조구등",
        "latin_name": "Uncaria rhynchophylla (Miq.) Miq. ex Havil.",
        "category": "평간식풍약",
        "properties": {"taste": "감미", "nature": "미한", "meridian": ["간", "심포"]},
        "description": "식풍정경, 청열평간에 사용. 갈고리 모양의 가시가 특징",
        "efficacy": "식풍정경, 청열평간",
        "precautions": "오래 달이면 약효 감소(후하). 혈압강하 작용으로 혈압약 병용 시 저혈압 가능.",
    },
    {
        "name": "지룡",
        "slug": "herbal-earthworm",
        "korean_name": "지룡",
        "latin_name": "Pheretima aspergillum (E.Perrier)",
        "category": "평간식풍약",
        "properties": {"taste": "함미", "nature": "한", "meridian": ["간", "비", "방광"]},
        "description": "청열식풍, 평천, 통락, 이뇨에 사용. 지렁이(건조 가공품)",
        "efficacy": "청열식풍, 통락, 평천, 이뇨",
        "precautions": "비위 허한 환자 주의. 혈압강하, 항응고 작용으로 관련 약물 병용 시 주의. 알레르기 반응 보고.",
    },
    {
        "name": "전갈",
        "slug": "herbal-scorpion",
        "korean_name": "전갈",
        "latin_name": "Buthus martensii Karsch",
        "category": "평간식풍약",
        "properties": {"taste": "신미", "nature": "평", "meridian": ["간"]},
        "description": "식풍지경, 통락지통, 공독산결에 사용. 전충(全蟲)",
        "efficacy": "식풍정경, 통락지통, 공독산결",
        "precautions": "독성 있음(신경독소). 용량 엄수. 임산부 금기. 혈허생풍(血虛生風) 환자 주의. 항경련제와 상호작용 가능.",
    },
    {
        "name": "오공",
        "slug": "herbal-centipede",
        "korean_name": "오공",
        "latin_name": "Scolopendra subspinipes mutilans L. Koch",
        "category": "평간식풍약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["간"]},
        "description": "식풍지경, 통락지통, 공독산결에 사용. 지네(건조품)",
        "efficacy": "식풍정경, 공독산결, 통락지통",
        "precautions": "독성 강함. 용량 엄수(일반 1~3g). 임산부 금기. 혈허생풍 환자 주의. 알레르기 반응 주의.",
    },
    {
        "name": "백강잠",
        "slug": "herbal-bombyx",
        "korean_name": "백강잠",
        "latin_name": "Bombyx mori L. (Beauveria bassiana 감염)",
        "category": "평간식풍약",
        "properties": {"taste": "함미, 신미", "nature": "평", "meridian": ["간", "폐", "위"]},
        "description": "식풍지경, 거풍지통, 화담산결에 사용. 백강균에 감염된 누에",
        "efficacy": "식풍정경, 거풍지통, 화담산결",
        "precautions": "진정 작용으로 진정제, 수면제 병용 시 과도한 진정 주의.",
    },

    # ================================================================
    # 13. 개규약(開竅藥) — +4
    # ================================================================
    {
        "name": "사향",
        "slug": "herbal-musk",
        "korean_name": "사향",
        "latin_name": "Moschus moschiferus L. (분비물)",
        "category": "개규약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["심", "비"]},
        "description": "개규성신, 활혈통경, 소종지통에 사용. CITES 규제 대상",
        "efficacy": "개규성신, 활혈통경, 소종지통",
        "precautions": "임산부 절대 금기(유산 유발). CITES 부속서 I — 인공 합성 대체재 사용 권장. 과량 시 중추신경 억제.",
    },
    {
        "name": "빙편",
        "slug": "herbal-borneol",
        "korean_name": "빙편",
        "latin_name": "Dryobalanops aromatica C.F.Gaertn. (결정)",
        "category": "개규약",
        "properties": {"taste": "신미, 고미", "nature": "미한", "meridian": ["심", "비", "폐"]},
        "description": "개규성신, 청열지통에 사용. 보르네올(borneol) 결정",
        "efficacy": "개규성신, 청열지통",
        "precautions": "임산부 주의. 기혈 허약 환자 주의. 피부·점막 자극 가능.",
    },
    {
        "name": "소합향",
        "slug": "herbal-styrax",
        "korean_name": "소합향",
        "latin_name": "Liquidambar orientalis Mill.",
        "category": "개규약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["심", "비"]},
        "description": "개규벽예, 거담, 온중지통에 사용. 소합향나무 수지",
        "efficacy": "개규, 벽예, 지통",
        "precautions": "음허화왕 환자 금기. 알레르기 반응 가능.",
    },
    {
        "name": "안식향",
        "slug": "herbal-benzoin",
        "korean_name": "안식향",
        "latin_name": "Styrax benzoin Dryand.",
        "category": "개규약",
        "properties": {"taste": "신미, 고미", "nature": "평", "meridian": ["심", "비"]},
        "description": "개규벽예, 행기활혈, 지통에 사용. 안식향나무 수지",
        "efficacy": "개규, 행기, 활혈, 지통",
        "precautions": "음허화왕, 실열 환자 주의. 접촉성 피부염 보고.",
    },

    # ================================================================
    # 14. 보음약(補陰藥) — +5 (여정자·상심자는 기존 존재)
    # ================================================================
    {
        "name": "천문동",
        "slug": "herbal-asparagus-root",
        "korean_name": "천문동",
        "latin_name": "Asparagus cochinchinensis (Lour.) Merr.",
        "category": "보음약",
        "properties": {"taste": "감미, 고미", "nature": "대한", "meridian": ["폐", "신"]},
        "description": "양음윤조, 청폐생진에 사용. 천문동 덩이뿌리",
        "efficacy": "양음윤조, 청폐강화",
        "precautions": "비위 허한, 설사 환자 금기. 풍한(風寒) 해수에 부적합.",
    },
    {
        "name": "옥죽",
        "slug": "herbal-polygonatum-odoratum",
        "korean_name": "옥죽",
        "latin_name": "Polygonatum odoratum (Mill.) Druce",
        "category": "보음약",
        "properties": {"taste": "감미", "nature": "미한", "meridian": ["폐", "위"]},
        "description": "양음윤조, 생진지갈에 사용하는 약재. 둥굴레",
        "efficacy": "양음윤폐, 생진양위",
        "precautions": "담습(痰濕) 기체, 비위 허한 환자 주의.",
    },
    {
        "name": "황정",
        "slug": "herbal-polygonatum",
        "korean_name": "황정",
        "latin_name": "Polygonatum sibiricum Delar. ex Redouté",
        "category": "보음약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["비", "폐", "신"]},
        "description": "보기양음, 건비, 윤폐, 익신에 사용. 층층둥굴레",
        "efficacy": "보기양음, 건비윤폐, 보신",
        "precautions": "담습(痰濕), 중만(中滿) 환자 주의. 혈당강하 작용 보고.",
    },
    {
        "name": "구판",
        "slug": "herbal-tortoise-shell",
        "korean_name": "구판",
        "latin_name": "Chinemys reevesii (Gray)",
        "category": "보음약",
        "properties": {"taste": "함미, 감미", "nature": "미한", "meridian": ["간", "신", "심"]},
        "description": "자음잠양, 보신건골, 양혈보심, 고경지붕에 사용. 거북 배껍질",
        "efficacy": "자음잠양, 보신건골, 양혈보심",
        "precautions": "비위 허한, 설사, 임산부 주의. 동물보호법 확인 필요.",
    },
    {
        "name": "별갑",
        "slug": "herbal-turtle-shell",
        "korean_name": "별갑",
        "latin_name": "Trionyx sinensis Wiegmann",
        "category": "보음약",
        "properties": {"taste": "함미", "nature": "미한", "meridian": ["간", "신"]},
        "description": "자음잠양, 퇴열제증, 연견산결에 사용. 자라 등껍질",
        "efficacy": "자음잠양, 퇴열제증, 연견산결",
        "precautions": "비위 허한, 설사, 임산부 주의. 음허무열(陰虛無熱) 환자 단독 사용 불필요.",
    },
    {
        "name": "한련초",
        "slug": "herbal-eclipta",
        "korean_name": "한련초",
        "latin_name": "Eclipta prostrata (L.) L.",
        "category": "보음약",
        "properties": {"taste": "감미, 산미", "nature": "한", "meridian": ["간", "신"]},
        "description": "자보간신, 양혈지혈에 사용. 한련초(旱蓮草)",
        "efficacy": "자보간신, 양혈지혈, 오수발",
        "precautions": "비위 허한, 설사 환자 주의. 특별한 약물 상호작용 보고 적음.",
    },

    # ================================================================
    # 15. 보양약(補陽藥) — +8
    # ================================================================
    {
        "name": "바극천",
        "slug": "herbal-morinda",
        "korean_name": "바극천",
        "latin_name": "Morinda officinalis F.C.How",
        "category": "보양약",
        "properties": {"taste": "감미, 신미", "nature": "미온", "meridian": ["신", "간"]},
        "description": "보신양, 강근골, 거풍습에 사용하는 약재",
        "efficacy": "보신조양, 강근골, 거풍습",
        "precautions": "음허화왕, 대변조결 환자 주의.",
    },
    {
        "name": "선모",
        "slug": "herbal-curculigo",
        "korean_name": "선모",
        "latin_name": "Curculigo orchioides Gaertn.",
        "category": "보양약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["신", "간", "비"]},
        "description": "보신양, 강근골, 거한습에 사용하는 약재",
        "efficacy": "보신조양, 강근골, 거한습",
        "precautions": "음허화왕 환자 금기. 독성 보고(과량 시 구토, 설사). 간독성 주의.",
    },
    {
        "name": "보골지",
        "slug": "herbal-psoralea",
        "korean_name": "보골지",
        "latin_name": "Psoralea corylifolia L.",
        "category": "보양약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["신", "비"]},
        "description": "보신조양, 고정축뇨, 온비지사에 사용. 파고지(破故紙)라고도 함",
        "efficacy": "보신조양, 고정축뇨, 온비지사, 납기평천",
        "precautions": "음허화왕 환자 금기. 프소랄렌(psoralen) 함유 — 광과민 반응 유발. 자외선 과다 노출 주의.",
    },
    {
        "name": "골쇄보",
        "slug": "herbal-drynaria",
        "korean_name": "골쇄보",
        "latin_name": "Drynaria fortunei (Kunze ex Mett.) J.Sm.",
        "category": "보양약",
        "properties": {"taste": "고미", "nature": "온", "meridian": ["신", "간"]},
        "description": "보신강골, 속근활혈에 사용. 고란초과 양치류",
        "efficacy": "보신, 활혈, 지혈, 속근상",
        "precautions": "음허내열, 혈허풍조 환자 주의.",
    },
    {
        "name": "속단",
        "slug": "herbal-dipsacus",
        "korean_name": "속단",
        "latin_name": "Dipsacus asperoides C.Y.Cheng et T.M.Ai",
        "category": "보양약",
        "properties": {"taste": "고미, 신미", "nature": "미온", "meridian": ["간", "신"]},
        "description": "보간신, 강근골, 속절상, 지붕루, 안태에 사용",
        "efficacy": "보간신, 속절상, 지붕루, 안태",
        "precautions": "특별한 금기 보고 적음. 화열(火熱)이 왕성한 환자 주의.",
    },
    {
        "name": "구척",
        "slug": "herbal-cibotium",
        "korean_name": "구척",
        "latin_name": "Cibotium barometz (L.) J.Sm.",
        "category": "보양약",
        "properties": {"taste": "고미, 감미", "nature": "온", "meridian": ["간", "신"]},
        "description": "보간신, 강요슬, 거풍습에 사용. 금모구척(金毛狗脊)",
        "efficacy": "보간신, 강요슬, 거풍습",
        "precautions": "신허유열(腎虛有熱), 소변불리 환자 주의.",
    },
    {
        "name": "자하거",
        "slug": "herbal-placenta",
        "korean_name": "자하거",
        "latin_name": "Homo sapiens (태반)",
        "category": "보양약",
        "properties": {"taste": "감미, 함미", "nature": "온", "meridian": ["심", "폐", "신"]},
        "description": "온신보정, 익기양혈에 사용. 인간 태반(건조 가공품)",
        "efficacy": "온신보정, 익기양혈",
        "precautions": "감염 위험(감염성 질환 전파 가능). 현대 의학에서는 안전성 논란. 법적 규제 확인 필수.",
    },
    {
        "name": "동충하초",
        "slug": "herbal-cordyceps",
        "korean_name": "동충하초",
        "latin_name": "Cordyceps sinensis (Berk.) Sacc.",
        "category": "보양약",
        "properties": {"taste": "감미", "nature": "온", "meridian": ["폐", "신"]},
        "description": "보폐익신, 지혈화담에 사용. 동충하초균이 기생한 곤충체",
        "efficacy": "보폐익신, 지혈화담",
        "precautions": "면역억제제(사이클로스포린 등) 병용 시 면역 반응 변동. 자가면역질환 환자 주의.",
    },

    # ================================================================
    # 16. 수삽약(收澀藥) — +7 (오미자는 기존 존재)
    # ================================================================
    {
        "name": "오매",
        "slug": "herbal-mume",
        "korean_name": "오매",
        "latin_name": "Prunus mume (Sieb.) Sieb. et Zucc.",
        "category": "수삽약",
        "properties": {"taste": "산미", "nature": "평", "meridian": ["간", "비", "폐", "대장"]},
        "description": "렴폐지해, 삽장지사, 안회지통, 생진지갈에 사용. 매실 훈제품",
        "efficacy": "렴폐, 삽장, 생진, 안회, 지혈",
        "precautions": "실열(實熱), 적체(積滯) 환자 금기. 위산과다 환자 과량 주의.",
    },
    {
        "name": "부소맥",
        "slug": "herbal-wheat-light",
        "korean_name": "부소맥",
        "latin_name": "Triticum aestivum L. (부양소맥)",
        "category": "수삽약",
        "properties": {"taste": "감미", "nature": "량", "meridian": ["심"]},
        "description": "고표지한, 익기, 제열에 사용. 가벼운(뜨는) 밀",
        "efficacy": "익기, 제열, 지한",
        "precautions": "글루텐 알레르기 환자 주의. 특별한 약물 상호작용 보고 적음.",
    },
    {
        "name": "마황근",
        "slug": "herbal-ephedra-root",
        "korean_name": "마황근",
        "latin_name": "Ephedra sinica Stapf (근)",
        "category": "수삽약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["폐"]},
        "description": "고표지한에 사용. 마황의 뿌리(지상부와 반대 작용 — 지한)",
        "efficacy": "고표지한",
        "precautions": "유한사(有汗邪)가 아직 있는 환자는 주의. 마황 지상부와 혼용 금지.",
    },
    {
        "name": "금앵자",
        "slug": "herbal-rosa-laevigata",
        "korean_name": "금앵자",
        "latin_name": "Rosa laevigata Michx.",
        "category": "수삽약",
        "properties": {"taste": "산미, 삽미", "nature": "평", "meridian": ["신", "방광", "대장"]},
        "description": "고정축뇨, 삽장지사에 사용. 금앵자(金櫻子) 열매",
        "efficacy": "고정축뇨, 삽장지사",
        "precautions": "실열(實熱) 환자 금기. 발열, 감기 초기 사용 불가.",
    },
    {
        "name": "복분자",
        "slug": "herbal-rubus",
        "korean_name": "복분자",
        "latin_name": "Rubus coreanus Miq.",
        "category": "수삽약",
        "properties": {"taste": "감미, 산미", "nature": "온", "meridian": ["간", "신"]},
        "description": "익신고정, 축뇨, 명목에 사용. 산딸기류",
        "efficacy": "보신조양, 고정축뇨",
        "precautions": "신허유열(腎虛有熱), 소변단적(小便短赤) 환자 주의.",
    },
    {
        "name": "상표초",
        "slug": "herbal-mantis-egg-case",
        "korean_name": "상표초",
        "latin_name": "Tenodera sinensis Saussure (난초)",
        "category": "수삽약",
        "properties": {"taste": "감미, 함미", "nature": "평", "meridian": ["간", "신"]},
        "description": "고정축뇨, 보신조양에 사용. 사마귀 알집",
        "efficacy": "고정축뇨, 보신조양",
        "precautions": "음허화왕, 방광습열 환자 금기.",
    },
    {
        "name": "해표초",
        "slug": "herbal-cuttlefish-bone",
        "korean_name": "해표초",
        "latin_name": "Sepiella maindroni de Rochebrune",
        "category": "수삽약",
        "properties": {"taste": "함미, 삽미", "nature": "미온", "meridian": ["간", "신"]},
        "description": "수삽지혈, 제산지통, 수습렴창에 사용. 오징어뼈",
        "efficacy": "수삽지혈, 제산, 렴창",
        "precautions": "음허다열(陰虛多熱) 환자 주의. 위산 중화 작용으로 제산제와 중복 사용 주의.",
    },

    # ================================================================
    # 17. 외용약(外用藥) — +5
    # ================================================================
    {
        "name": "유황",
        "slug": "herbal-sulfur",
        "korean_name": "유황",
        "latin_name": "Sulfur (S)",
        "category": "외용약",
        "properties": {"taste": "산미", "nature": "온", "meridian": ["신", "대장"]},
        "description": "외용으로 살충지양, 내복으로 보화조양, 통변에 사용. 광물성 약재",
        "efficacy": "해독살충(외용), 보화조양(내복), 통변",
        "precautions": "내복 시 독성 주의(용량 엄수). 간·신 독성. 피부 자극 강함. 임산부 금기.",
    },
    {
        "name": "명반",
        "slug": "herbal-alum",
        "korean_name": "명반",
        "latin_name": "KAl(SO4)2·12H2O (Alumen)",
        "category": "외용약",
        "properties": {"taste": "산미, 삽미", "nature": "한", "meridian": ["폐", "간", "비", "대장"]},
        "description": "외용으로 해독살충, 조습지양에 사용하는 광물성 약재",
        "efficacy": "해독살충, 조습지양, 지혈지사",
        "precautions": "알루미늄 함유 — 장기 복용 금지(신경독성, 골연화). 신장 질환 환자 금기.",
    },
    {
        "name": "웅황",
        "slug": "herbal-realgar",
        "korean_name": "웅황",
        "latin_name": "As2S2 (Realgar)",
        "category": "외용약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["심", "간", "위"]},
        "description": "해독, 살충에 사용하는 광물성 약재. 비소(As) 함유",
        "efficacy": "해독, 살충, 조습, 거담",
        "precautions": "비소 함유 — 독성 극강. 내복 극소량만 허용. 간·신 독성. 임산부 절대 금기. 현대 의학에서 사용 제한 권고.",
    },
    {
        "name": "붕사",
        "slug": "herbal-borax",
        "korean_name": "붕사",
        "latin_name": "Na2B4O7·10H2O (Borax)",
        "category": "외용약",
        "properties": {"taste": "감미, 함미", "nature": "량", "meridian": ["폐", "위"]},
        "description": "외용으로 청열소담, 해독방부에 사용. 구내염, 인후통에 활용",
        "efficacy": "청열소담, 해독방부",
        "precautions": "내복 시 독성(중추신경, 소화기 장애). 피부·점막 자극. 임산부 금기.",
    },
    {
        "name": "사상자",
        "slug": "herbal-cnidium-fruit",
        "korean_name": "사상자",
        "latin_name": "Cnidium monnieri (L.) Cuss.",
        "category": "외용약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["신"]},
        "description": "외용으로 살충지양, 내복으로 온신조양에 사용",
        "efficacy": "온신조양(내복), 살충지양(외용), 조습",
        "precautions": "음허화왕, 하초유열 환자 금기. 피부 자극 가능.",
    },

    # ================================================================
    # 18. 보기약(補氣藥) — +4 (대조는 기존 존재)
    # ================================================================
    {
        "name": "당삼",
        "slug": "herbal-codonopsis",
        "korean_name": "당삼",
        "latin_name": "Codonopsis pilosula (Franch.) Nannf.",
        "category": "보기약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["비", "폐"]},
        "description": "보중익기, 건비익폐에 사용. 인삼의 대용품으로 다용",
        "efficacy": "보중익기, 건비익폐, 양혈생진",
        "precautions": "실증(實證), 열증 환자 주의. 여로(藜蘆)와 배합 금기.",
    },
    {
        "name": "태자삼",
        "slug": "herbal-pseudostellaria",
        "korean_name": "태자삼",
        "latin_name": "Pseudostellaria heterophylla (Miq.) Pax ex Pax et Hoffm.",
        "category": "보기약",
        "properties": {"taste": "감미, 미고미", "nature": "평", "meridian": ["비", "폐"]},
        "description": "보기건비, 생진윤폐에 사용. 소아 보기약으로 다용(작용 온화)",
        "efficacy": "보기건비, 생진윤폐",
        "precautions": "사기(邪氣)가 왕성한 실증에는 부적합. 특별한 약물 상호작용 보고 적음.",
    },
    {
        "name": "서양삼",
        "slug": "herbal-american-ginseng",
        "korean_name": "서양삼",
        "latin_name": "Panax quinquefolius L.",
        "category": "보기약",
        "properties": {"taste": "감미, 미고미", "nature": "량", "meridian": ["심", "폐", "신"]},
        "description": "보기양음, 청화생진에 사용. 기허(氣虛)와 음허(陰虛)를 겸한 경우에 적합",
        "efficacy": "보기양음, 청화생진",
        "precautions": "양허(陽虛) 환자, 감기 초기 주의. 항응고제 병용 시 출혈 위험(인삼류 공통). 면역억제제와 병용 주의.",
    },
    {
        "name": "영지",
        "slug": "herbal-ganoderma",
        "korean_name": "영지",
        "latin_name": "Ganoderma lucidum (Curtis) P.Karst.",
        "category": "보기약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["심", "폐", "간", "신"]},
        "description": "보기안신, 지해평천에 사용. 영지버섯",
        "efficacy": "보기안신, 지해평천, 보중강장",
        "precautions": "면역억제제 병용 시 면역 반응 변동. 항응고제 병용 시 출혈 위험. 수술 2주 전 중단 권장.",
    },

    # ================================================================
    # 19. 보혈약(補血藥) — +3 (용안육·자하거는 기존/위에 존재, 상심자 추가)
    # ================================================================
    {
        "name": "계혈등",
        "slug": "herbal-spatholobus",
        "korean_name": "계혈등",
        "latin_name": "Spatholobus suberectus Dunn",
        "category": "보혈약",
        "properties": {"taste": "고미, 감미", "nature": "온", "meridian": ["간", "신"]},
        "description": "활혈보혈, 조경통락에 사용. 콩과 등본(藤本) 식물",
        "efficacy": "활혈보혈, 조경, 서근활락",
        "precautions": "임산부 주의. 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "상심자",
        "slug": "herbal-mulberry-fruit",
        "korean_name": "상심자",
        "latin_name": "Morus alba L. (과수)",
        "category": "보혈약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["심", "간", "신"]},
        "description": "보혈자음, 생진윤장에 사용. 오디(뽕나무 열매)",
        "efficacy": "자음보혈, 생진윤조",
        "precautions": "비위 허한, 설사 환자 주의. 혈당강하 작용 보고.",
    },
    {
        "name": "흑지마",
        "slug": "herbal-black-sesame",
        "korean_name": "흑지마",
        "latin_name": "Sesamum indicum L.",
        "category": "보혈약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["간", "신", "대장"]},
        "description": "보간신, 윤오장, 익정혈에 사용. 검은 참깨",
        "efficacy": "보간신, 익정혈, 윤장조",
        "precautions": "설사 환자 과량 주의. 특별한 약물 상호작용 보고 적음.",
    },

    # ================================================================
    # 20. 활혈거어약(活血祛瘀藥) — +6 (우슬은 거풍습약에 존재, 울금·강황 추가)
    # ================================================================
    {
        "name": "익모초",
        "slug": "herbal-leonurus",
        "korean_name": "익모초",
        "latin_name": "Leonurus japonicus Houtt.",
        "category": "활혈거어약",
        "properties": {"taste": "신미, 고미", "nature": "미한", "meridian": ["심", "간", "방광"]},
        "description": "활혈조경, 이뇨소종에 사용. 여성 질환의 요약(익모=어머니를 이롭게 함)",
        "efficacy": "활혈조경, 이뇨소종, 청열해독",
        "precautions": "임산부 주의(자궁수축 촉진). 음허혈소(陰虛血少) 환자 단독 사용 금지.",
    },
    {
        "name": "왕불류행",
        "slug": "herbal-vaccaria",
        "korean_name": "왕불류행",
        "latin_name": "Vaccaria segetalis (Neck.) Garcke",
        "category": "활혈거어약",
        "properties": {"taste": "고미", "nature": "평", "meridian": ["간", "위"]},
        "description": "활혈통경, 하유소옹에 사용. 왕불류행(王不留行) 종자",
        "efficacy": "활혈통경, 하유, 소옹",
        "precautions": "임산부 금기. 월경과다 환자 주의.",
    },
    {
        "name": "울금",
        "slug": "herbal-curcuma-tuber",
        "korean_name": "울금",
        "latin_name": "Curcuma wenyujin Y.H.Chen et C.Ling",
        "category": "활혈거어약",
        "properties": {"taste": "신미, 고미", "nature": "한", "meridian": ["심", "간", "담"]},
        "description": "활혈지통, 행기해울, 청심양혈, 이담퇴황에 사용",
        "efficacy": "활혈지통, 행기해울, 청심양혈, 이담퇴황",
        "precautions": "임산부 주의. 항응고제 병용 시 출혈 위험. 정향(丁香)과 배합 시 약효 상충(십구외).",
    },
    {
        "name": "강황",
        "slug": "herbal-turmeric",
        "korean_name": "강황",
        "latin_name": "Curcuma longa L.",
        "category": "활혈거어약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["비", "간"]},
        "description": "파혈행기, 통경지통에 사용. 카레의 주원료(커큐민 함유)",
        "efficacy": "파혈행기, 통경지통",
        "precautions": "임산부 주의. 항응고제(와파린) 병용 시 출혈 위험. 담도폐쇄 환자 금기. CYP 효소에 영향 가능.",
    },
    {
        "name": "아출",
        "slug": "herbal-curcuma-zedoaria",
        "korean_name": "아출",
        "latin_name": "Curcuma phaeocaulis Valeton",
        "category": "활혈거어약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["간", "비"]},
        "description": "파혈행기, 소적지통에 사용하는 약재. 봉출(蓬朮)이라고도 함",
        "efficacy": "파혈행기, 소적지통",
        "precautions": "임산부 금기. 월경과다 환자 주의. 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "삼릉",
        "slug": "herbal-sparganium",
        "korean_name": "삼릉",
        "latin_name": "Sparganium stoloniferum (Graebn.) Buch.-Ham. ex Juz.",
        "category": "활혈거어약",
        "properties": {"taste": "신미, 고미", "nature": "평", "meridian": ["간", "비"]},
        "description": "파혈행기, 소적지통에 사용. 아출과 함께 사용 빈도 높음",
        "efficacy": "파혈행기, 소적지통",
        "precautions": "임산부 금기. 월경과다 환자 주의. 체허무어(體虛無瘀) 환자 금기.",
    },
    {
        "name": "수질",
        "slug": "herbal-hirudo",
        "korean_name": "수질",
        "latin_name": "Hirudo nipponica Whitman",
        "category": "활혈거어약",
        "properties": {"taste": "함미, 고미", "nature": "평", "meridian": ["간"]},
        "description": "파혈축어, 통경에 사용. 거머리(건조 가공품). 히루딘(hirudin) 함유",
        "efficacy": "파혈축어, 통경",
        "precautions": "임산부 절대 금기. 출혈 경향 환자 금기. 항응고제 병용 시 출혈 위험 극대. 히루딘의 강력한 항트롬빈 작용.",
    },

    # ================================================================
    # 21. 기타 — 추가 약재 (+15)
    # ================================================================
    {
        "name": "천남성",
        "slug": "herbal-arisaema",
        "korean_name": "천남성",
        "latin_name": "Arisaema erubescens (Wall.) Schott",
        "category": "화담약",
        "properties": {"taste": "고미, 신미", "nature": "온", "meridian": ["폐", "간", "비"]},
        "description": "조습화담, 거풍지경, 산결소종에 사용. 독성 강하여 법제 필수",
        "efficacy": "조습화담, 거풍지경, 산결소종",
        "precautions": "독성 강함(생용 금지, 법제 필수). 임산부 금기. 음허조담(陰虛燥痰) 환자 금기.",
    },
    {
        "name": "죽여",
        "slug": "herbal-bamboo-shavings",
        "korean_name": "죽여",
        "latin_name": "Bambusa tuldoides Munro",
        "category": "화담약",
        "properties": {"taste": "감미", "nature": "미한", "meridian": ["폐", "위", "심"]},
        "description": "청화열담, 제번지구에 사용. 대나무 줄기의 속껍질",
        "efficacy": "청화열담, 제번지구",
        "precautions": "한담(寒痰), 습담(濕痰) 환자 부적합. 비위 허한 환자 주의.",
    },
    {
        "name": "대계",
        "slug": "herbal-cirsium",
        "korean_name": "대계",
        "latin_name": "Cirsium japonicum Fisch. ex DC.",
        "category": "지혈약",
        "properties": {"taste": "감미, 고미", "nature": "량", "meridian": ["심", "간"]},
        "description": "양혈지혈, 산어해독소옹에 사용. 엉겅퀴",
        "efficacy": "양혈지혈, 산어해독소옹",
        "precautions": "비위 허한, 무어혈(無瘀血) 환자 주의.",
    },
    {
        "name": "소계",
        "slug": "herbal-cirsium-small",
        "korean_name": "소계",
        "latin_name": "Cirsium setidens (Dunn) Nakai",
        "category": "지혈약",
        "properties": {"taste": "감미, 고미", "nature": "량", "meridian": ["심", "간"]},
        "description": "양혈지혈, 산어소옹에 사용. 조뱅이",
        "efficacy": "양혈지혈, 산어소옹",
        "precautions": "비위 허한, 혈허(血虛) 환자 주의.",
    },
    {
        "name": "측백엽",
        "slug": "herbal-biota-leaf",
        "korean_name": "측백엽",
        "latin_name": "Platycladus orientalis (L.) Franco (葉)",
        "category": "지혈약",
        "properties": {"taste": "고미, 삽미", "nature": "미한", "meridian": ["폐", "간", "비"]},
        "description": "양혈지혈, 지해거담에 사용. 측백나무 잎",
        "efficacy": "양혈지혈, 화담지해, 생발오발",
        "precautions": "다량의 정유(精油) 함유. 위장 장애 가능. 습담(濕痰) 환자 주의.",
    },
    {
        "name": "포황",
        "slug": "herbal-typha-pollen",
        "korean_name": "포황",
        "latin_name": "Typha angustifolia L.",
        "category": "지혈약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["간", "심포"]},
        "description": "지혈, 화어, 통림에 사용. 부들 꽃가루",
        "efficacy": "지혈화어, 통림",
        "precautions": "임산부 주의. 항응고제 병용 시 주의(지혈 + 화어 양면 작용).",
    },
    {
        "name": "백급",
        "slug": "herbal-bletilla",
        "korean_name": "백급",
        "latin_name": "Bletilla striata (Thunb.) Rchb.f.",
        "category": "지혈약",
        "properties": {"taste": "고미, 감미, 삽미", "nature": "미한", "meridian": ["폐", "간", "위"]},
        "description": "수렴지혈, 소종생기에 사용. 난초과 식물의 덩이줄기",
        "efficacy": "수렴지혈, 소종생기",
        "precautions": "오두(烏頭)와 배합 금기(십팔반). 외감(外感) 해수에는 부적합.",
    },
    {
        "name": "용골",
        "slug": "herbal-dragon-bone",
        "korean_name": "용골",
        "latin_name": "Os Draconis (화석화된 포유류 골)",
        "category": "안신약",
        "properties": {"taste": "감미, 삽미", "nature": "평", "meridian": ["심", "간", "신"]},
        "description": "진정안신, 평간잠양, 수삽고정에 사용. 고대 포유류 화석골",
        "efficacy": "진정안신, 평간잠양, 수삽고탈",
        "precautions": "습열(濕熱) 환자 주의. 석고 등 광물성 약과 유사하게 분쇄 후 선전(先煎) 필요.",
    },
    {
        "name": "모려",
        "slug": "herbal-oyster-shell",
        "korean_name": "모려",
        "latin_name": "Ostrea gigas Thunberg",
        "category": "안신약",
        "properties": {"taste": "함미, 삽미", "nature": "미한", "meridian": ["간", "담", "신"]},
        "description": "평간잠양, 연견산결, 수삽고정에 사용. 굴 껍데기",
        "efficacy": "평간잠양, 연견산결, 제산지통, 수삽고탈",
        "precautions": "선전(先煎) 필수. 칼슘제와 중복 사용 주의. 특별한 약물 상호작용 보고 적음.",
    },
    {
        "name": "주사",
        "slug": "herbal-cinnabar",
        "korean_name": "주사",
        "latin_name": "HgS (Cinnabaris)",
        "category": "안신약",
        "properties": {"taste": "감미", "nature": "미한", "meridian": ["심"]},
        "description": "진심안신, 청열해독에 사용하는 광물성 약재",
        "efficacy": "진심안신, 청열해독",
        "precautions": "수은(Hg) 함유 — 독성 극강. 내복 극소량·단기간만 허용. 간·신 독성. 현대 의학에서 사용 극도로 제한.",
    },
    {
        "name": "호장근",
        "slug": "herbal-polygonum-cuspidatum",
        "korean_name": "호장근",
        "latin_name": "Reynoutria japonica Houtt.",
        "category": "활혈거어약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["간", "담", "폐"]},
        "description": "활혈산어, 거풍이습, 해독에 사용. 레스베라트롤 함유",
        "efficacy": "활혈산어, 청열이습, 해독화담, 지해",
        "precautions": "임산부 금기. 이모딘(emodin) 함유 — 사하 작용. 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "자연동",
        "slug": "herbal-pyrite",
        "korean_name": "자연동",
        "latin_name": "Pyritum (FeS2)",
        "category": "활혈거어약",
        "properties": {"taste": "신미", "nature": "평", "meridian": ["간"]},
        "description": "산어지통, 접골속근에 사용. 황철광 광물",
        "efficacy": "산어지통, 접골속근",
        "precautions": "무어혈(無瘀血) 환자 불필요. 중금속 함유 가능 — 순도 확인 필수.",
    },
    {
        "name": "유향",
        "slug": "herbal-frankincense",
        "korean_name": "유향",
        "latin_name": "Boswellia carterii Birdw.",
        "category": "활혈거어약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["심", "간", "비"]},
        "description": "활혈행기, 지통, 소종생기에 사용. 유향나무 수지",
        "efficacy": "활혈행기지통, 소종생기",
        "precautions": "임산부 금기. 위장 자극(구역, 구토 가능). 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "몰약",
        "slug": "herbal-myrrh",
        "korean_name": "몰약",
        "latin_name": "Commiphora myrrha (Nees) Engl.",
        "category": "활혈거어약",
        "properties": {"taste": "고미", "nature": "평", "meridian": ["심", "간", "비"]},
        "description": "산어지통, 소종생기에 사용. 유향과 함께 사용 빈도 높음(유향-몰약 상수)",
        "efficacy": "산어지통, 소종생기",
        "precautions": "임산부 금기. 위장 자극. 항응고제 병용 시 출혈 위험. 혈당강하 작용 보고.",
    },
    {
        "name": "택란",
        "slug": "herbal-lycopus",
        "korean_name": "택란",
        "latin_name": "Lycopus lucidus Turcz.",
        "category": "활혈거어약",
        "properties": {"taste": "고미, 신미", "nature": "미온", "meridian": ["간", "비"]},
        "description": "활혈거어, 행수소종에 사용하는 약재. 쉽사리",
        "efficacy": "활혈거어, 행수소종",
        "precautions": "혈허(血虛) 무어(無瘀) 환자 주의. 임산부 주의.",
    },

    # ================================================================
    # 22. 추가 약재 — 기타 분류 보강 (+36)
    # ================================================================
    # ── 이기약 보충 ──
    {
        "name": "시라자",
        "slug": "herbal-dalbergia",
        "korean_name": "시라자",
        "latin_name": "Dalbergia odorifera T.Chen",
        "category": "이기약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["심", "간", "비"]},
        "description": "행기활혈, 지통지혈에 사용. 강진향(降眞香)이라고도 함",
        "efficacy": "행기활혈, 지통지혈",
        "precautions": "음허화왕, 혈열(血熱) 환자 주의.",
    },
    {
        "name": "도두",
        "slug": "herbal-litchi-seed",
        "korean_name": "여지핵",
        "latin_name": "Litchi chinensis Sonn. (핵)",
        "category": "이기약",
        "properties": {"taste": "감미, 삽미", "nature": "온", "meridian": ["간", "신"]},
        "description": "행기산결, 산한지통에 사용. 리치(여지) 씨앗",
        "efficacy": "행기산결, 거한지통",
        "precautions": "무한기(無寒氣) 환자는 불필요.",
    },
    # ── 화담약 보충 ──
    {
        "name": "과루피",
        "slug": "herbal-trichosanthes-peel",
        "korean_name": "과루피",
        "latin_name": "Trichosanthes kirilowii Maxim. (과피)",
        "category": "화담약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["폐", "위"]},
        "description": "청화열담, 이기관흉에 사용. 하늘타리 열매 껍질",
        "efficacy": "청화열담, 이기관흉",
        "precautions": "비위 허한, 한담(寒痰) 환자 부적합. 오두(烏頭)와 배합 금기.",
    },
    {
        "name": "담남성",
        "slug": "herbal-arisaema-bile",
        "korean_name": "담남성",
        "latin_name": "Arisaema cum Bile (담즙 법제)",
        "category": "화담약",
        "properties": {"taste": "고미, 미신미", "nature": "량", "meridian": ["폐", "간"]},
        "description": "청열화담, 식풍정경에 사용. 천남성을 소(牛)담즙으로 법제한 것",
        "efficacy": "청열화담, 식풍정경",
        "precautions": "비위 허한, 한담 환자 부적합.",
    },
    {
        "name": "해조",
        "slug": "herbal-sargassum",
        "korean_name": "해조",
        "latin_name": "Sargassum pallidum (Turn.) C.Ag.",
        "category": "화담약",
        "properties": {"taste": "고미, 함미", "nature": "한", "meridian": ["간", "위", "신"]},
        "description": "소담연견, 이수소종에 사용. 해조류",
        "efficacy": "소담연견, 이수소종",
        "precautions": "비위 허한 환자 주의. 요오드 함유로 갑상선 질환 약물 병용 주의. 감초와 배합 금기(십팔반).",
    },
    {
        "name": "곤포",
        "slug": "herbal-laminaria",
        "korean_name": "곤포",
        "latin_name": "Laminaria japonica Areschoug",
        "category": "화담약",
        "properties": {"taste": "함미", "nature": "한", "meridian": ["간", "위", "신"]},
        "description": "소담연견, 이수소종에 사용. 다시마",
        "efficacy": "소담연견, 이수퇴종",
        "precautions": "비위 허한 환자 주의. 요오드 다량 함유 — 갑상선 약물 병용 주의.",
    },
    {
        "name": "와릉자",
        "slug": "herbal-arca-shell",
        "korean_name": "와릉자",
        "latin_name": "Arca granosa L.",
        "category": "화담약",
        "properties": {"taste": "함미", "nature": "평", "meridian": ["폐", "위", "간"]},
        "description": "소담화어, 연견산결, 제산지통에 사용. 꼬막 껍데기",
        "efficacy": "소담화어, 연견산결, 제산",
        "precautions": "특별한 금기 보고 적음. 선전(先煎) 필요.",
    },
    # ── 거풍습약 보충 ──
    {
        "name": "잠사",
        "slug": "herbal-silkworm-excrement",
        "korean_name": "잠사",
        "latin_name": "Bombyx mori L. (분변)",
        "category": "거풍습약",
        "properties": {"taste": "감미, 신미", "nature": "온", "meridian": ["간", "비", "위"]},
        "description": "거풍습, 화습탁, 화위에 사용. 누에 배설물(잠사/잠분)",
        "efficacy": "거풍습, 화습탁, 화위",
        "precautions": "특별한 금기 보고 적음.",
    },
    {
        "name": "목과",
        "slug": "herbal-chaenomeles",
        "korean_name": "목과",
        "latin_name": "Chaenomeles speciosa (Sweet) Nakai",
        "category": "거풍습약",
        "properties": {"taste": "산미", "nature": "온", "meridian": ["간", "비"]},
        "description": "서근활락, 화습화위에 사용. 모과(산당화) 열매",
        "efficacy": "서근활락, 화습화위",
        "precautions": "위산과다 환자 주의. 소변불리·내열 환자 주의.",
    },
    {
        "name": "호골",
        "slug": "herbal-tiger-bone-sub",
        "korean_name": "호골(대체재)",
        "latin_name": "대체재 사용 — CITES 규제",
        "category": "거풍습약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["간", "신"]},
        "description": "거풍통비, 강근골에 사용되었으나 CITES 규제로 사용 금지. 대체재(개뼈 등) 사용",
        "efficacy": "거풍정통, 강근골(전통 기록)",
        "precautions": "호랑이 CITES 부속서 I — 절대 사용 금지. 대체재(구골·구척 등)로 대체.",
    },
    # ── 온리약 보충 ──
    {
        "name": "육계",
        "slug": "herbal-cinnamon-bark",
        "korean_name": "육계",
        "latin_name": "Cinnamomum cassia (L.) J.Presl (수피)",
        "category": "온리약",
        "properties": {"taste": "신미, 감미", "nature": "대열", "meridian": ["신", "비", "심", "간"]},
        "description": "보화조양, 인화귀원, 산한지통, 온경통맥에 사용. 계피(桂皮) 껍질",
        "efficacy": "보화조양, 인화귀원, 산한지통, 온경통맥",
        "precautions": "음허화왕, 혈열 환자 금기. 임산부 금기. 쿠마린 함유 — 항응고제(와파린) 병용 시 출혈 위험.",
    },
    {
        "name": "오두",
        "slug": "herbal-aconite-mother",
        "korean_name": "오두",
        "latin_name": "Aconitum carmichaeli Debeaux (모근)",
        "category": "온리약",
        "properties": {"taste": "신미, 고미", "nature": "열", "meridian": ["심", "비", "간", "신"]},
        "description": "거풍제습, 온경지통에 사용. 부자의 모근. 독성 극강",
        "efficacy": "거한습, 지통",
        "precautions": "독성 극강(아코니틴). 법제 필수. 반하·과루·패모·백렴·백급과 배합 금기(십팔반). 임산부 절대 금기.",
    },
    # ── 수삽약 보충 ──
    {
        "name": "연자육",
        "slug": "herbal-lotus-seed",
        "korean_name": "연자육",
        "latin_name": "Nelumbo nucifera Gaertn. (종자)",
        "category": "수삽약",
        "properties": {"taste": "감미, 삽미", "nature": "평", "meridian": ["비", "신", "심"]},
        "description": "보비지사, 보신삽정, 양심안신에 사용. 연꽃 씨",
        "efficacy": "보비지사, 익신고정, 보심안신",
        "precautions": "대변조결(大便燥結), 중만복창(中滿腹脹) 환자 주의.",
    },
    {
        "name": "연자심",
        "slug": "herbal-lotus-plumule",
        "korean_name": "연자심",
        "latin_name": "Nelumbo nucifera Gaertn. (배아)",
        "category": "수삽약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["심", "신"]},
        "description": "청심거열, 지혈삽정에 사용. 연꽃 씨의 심(胚芽)",
        "efficacy": "청심안신, 교통심신, 삽정지혈",
        "precautions": "비위 허한 환자 주의. 대변조결 환자 부적합.",
    },
    {
        "name": "육두구",
        "slug": "herbal-nutmeg",
        "korean_name": "육두구",
        "latin_name": "Myristica fragrans Houtt.",
        "category": "수삽약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["비", "위", "대장"]},
        "description": "온중행기, 삽장지사에 사용. 육두구(넛메그) 종자",
        "efficacy": "온중행기, 삽장지사",
        "precautions": "습열사제(濕熱邪滯), 실열(實熱) 설사 환자 금기. 과량 시 환각 작용(미리스티신 함유).",
    },
    {
        "name": "가자",
        "slug": "herbal-terminalia",
        "korean_name": "가자",
        "latin_name": "Terminalia chebula Retz.",
        "category": "수삽약",
        "properties": {"taste": "고미, 산미, 삽미", "nature": "평", "meridian": ["폐", "대장"]},
        "description": "삽장지사, 렴폐지해, 이인개음에 사용. 가자(訶子) 열매",
        "efficacy": "삽장지사, 렴폐지해, 강기이인",
        "precautions": "외감(外感) 해수, 실열(實熱) 설사에는 부적합.",
    },
    # ── 청열약 보충 ──
    {
        "name": "사간",
        "slug": "herbal-belamcanda",
        "korean_name": "사간",
        "latin_name": "Belamcanda chinensis (L.) Redouté",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["폐"]},
        "description": "청열해독, 이인후, 소담에 사용. 범부채 뿌리줄기",
        "efficacy": "청열해독, 소담이인",
        "precautions": "비위 허한, 임산부 주의. 이리딘(iridin) 함유 — 과량 시 구토, 설사.",
    },
    {
        "name": "산두근",
        "slug": "herbal-sophora-tonkinensis",
        "korean_name": "산두근",
        "latin_name": "Sophora tonkinensis Gagnep.",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["폐", "위"]},
        "description": "청열해독, 이인후에 사용. 인후종통의 요약",
        "efficacy": "청열해독, 이인소종",
        "precautions": "비위 허한 환자 금기. 독성 보고(마트린 함유). 과량 시 구토, 복통.",
    },
    {
        "name": "백화사설초",
        "slug": "herbal-hedyotis",
        "korean_name": "백화사설초",
        "latin_name": "Hedyotis diffusa Willd.",
        "category": "청열약",
        "properties": {"taste": "고미, 감미", "nature": "한", "meridian": ["위", "대장", "소장"]},
        "description": "청열해독, 이습통림, 항암 연구 활발. 현대 중의학에서 종양 보조치료에 활용",
        "efficacy": "청열해독, 이습통림, 소옹산결",
        "precautions": "비위 허한 환자 주의. 항암 목적 단독 사용 불가(의사 감독 하에 보조적 사용).",
    },
    {
        "name": "마치현",
        "slug": "herbal-portulaca",
        "korean_name": "마치현",
        "latin_name": "Portulaca oleracea L.",
        "category": "청열약",
        "properties": {"taste": "산미", "nature": "한", "meridian": ["간", "대장"]},
        "description": "청열해독, 양혈지리에 사용. 쇠비름(식용 가능)",
        "efficacy": "청열해독, 양혈지리, 소종",
        "precautions": "비위 허한, 설사 환자 주의. 임산부 주의(자궁수축 가능). 옥살산 함유 — 신결석 주의.",
    },
    # ── 보음약 보충 ──
    {
        "name": "남사삼",
        "slug": "herbal-adenophora-southern",
        "korean_name": "남사삼",
        "latin_name": "Adenophora tetraphylla (Thunb.) Fisch.",
        "category": "보음약",
        "properties": {"taste": "감미", "nature": "미한", "meridian": ["폐", "위"]},
        "description": "양음청폐, 익위생진, 화담, 익기에 사용",
        "efficacy": "양음청폐, 익위생진, 화담",
        "precautions": "풍한(風寒) 해수, 담(痰)이 왕성한 환자 부적합. 여로(藜蘆)와 배합 금기.",
    },
    {
        "name": "철피석곡",
        "slug": "herbal-dendrobium-iron",
        "korean_name": "철피석곡",
        "latin_name": "Dendrobium officinale Kimura et Migo",
        "category": "보음약",
        "properties": {"taste": "감미", "nature": "미한", "meridian": ["위", "신"]},
        "description": "익위생진, 자음청열에 사용. 석곡류 중 최고 품질로 평가",
        "efficacy": "익위생진, 자음청열",
        "precautions": "온열병(溫熱病) 초기, 습온(濕溫) 환자 주의.",
    },
    # ── 보양약 보충 ──
    {
        "name": "익지인",
        "slug": "herbal-alpinia-oxyphylla",
        "korean_name": "익지인",
        "latin_name": "Alpinia oxyphylla Miq.",
        "category": "보양약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["비", "신"]},
        "description": "온비지사, 난신축뇨, 고정삽정에 사용. 생강과 식물의 종자",
        "efficacy": "온비지사, 보신고정, 축뇨타액",
        "precautions": "음허화왕, 열증 환자 금기.",
    },
    {
        "name": "해마",
        "slug": "herbal-seahorse",
        "korean_name": "해마",
        "latin_name": "Hippocampus kelloggi Jordan et Snyder",
        "category": "보양약",
        "properties": {"taste": "감미, 함미", "nature": "온", "meridian": ["간", "신"]},
        "description": "보신조양, 조혈축뇨, 산결소종에 사용. CITES 규제 대상",
        "efficacy": "보신조양, 활혈산결",
        "precautions": "음허화왕 환자 금기. CITES 부속서 II 등재 — 합법적 조달 확인 필수.",
    },
    {
        "name": "하수오등",
        "slug": "herbal-polygonum-vine",
        "korean_name": "야교등",
        "latin_name": "Polygonum multiflorum Thunb. (등)",
        "category": "안신약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["심", "간"]},
        "description": "양심안신, 거풍통락에 사용. 하수오의 줄기(야교등)",
        "efficacy": "양심안신, 거풍통락",
        "precautions": "특별한 금기 보고 적음. 하수오 뿌리보다 간독성 위험 낮음.",
    },
    # ── 지혈약 보충 ──
    {
        "name": "삼백초",
        "slug": "herbal-saururus",
        "korean_name": "삼백초",
        "latin_name": "Saururus chinensis (Lour.) Baill.",
        "category": "지혈약",
        "properties": {"taste": "감미, 신미", "nature": "한", "meridian": ["폐", "방광"]},
        "description": "이뇨통림, 청열해독에 사용. 삼백초과 식물",
        "efficacy": "이뇨, 해독, 청열",
        "precautions": "비위 허한 환자 주의.",
    },
    {
        "name": "선학초",
        "slug": "herbal-agrimonia",
        "korean_name": "선학초",
        "latin_name": "Agrimonia pilosa Ledeb.",
        "category": "지혈약",
        "properties": {"taste": "고미, 삽미", "nature": "평", "meridian": ["폐", "간", "비"]},
        "description": "수렴지혈, 해독, 살충, 보허에 사용. 짚신나물",
        "efficacy": "수렴지혈, 지리, 살충, 보허",
        "precautions": "특별한 금기 보고 적음. 탄닌 함유로 철분 흡수 저해 가능.",
    },
    # ── 리수삼습약 보충 ──
    {
        "name": "인진호",
        "slug": "herbal-artemisia-capillaris",
        "korean_name": "인진호",
        "latin_name": "Artemisia capillaris Thunb.",
        "category": "이수삼습약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["비", "위", "간", "담"]},
        "description": "청이습열, 퇴황에 사용. 황달(黃疸)의 요약. 사철쑥",
        "efficacy": "청열이습, 퇴황",
        "precautions": "비위 허한, 음허(陰虛) 환자 주의. 특별한 약물 상호작용 보고 적음.",
    },
    {
        "name": "금전초",
        "slug": "herbal-lysimachia",
        "korean_name": "금전초",
        "latin_name": "Lysimachia christinae Hance",
        "category": "이수삼습약",
        "properties": {"taste": "감미, 함미", "nature": "미한", "meridian": ["간", "담", "신", "방광"]},
        "description": "이습퇴황, 이뇨통림, 해독소종에 사용. 결석(結石)에 다용",
        "efficacy": "이습퇴황, 이뇨통림, 해독소종",
        "precautions": "비위 허한 환자 주의. 이뇨제와 병용 시 전해질 불균형 가능.",
    },
    # ── 지해평천약 보충 ──
    {
        "name": "선복화",
        "slug": "herbal-inula",
        "korean_name": "선복화",
        "latin_name": "Inula japonica Thunb.",
        "category": "지해평천약",
        "properties": {"taste": "고미, 신미, 함미", "nature": "미온", "meridian": ["폐", "위", "대장"]},
        "description": "강기지구, 화담개결에 사용. 국화과 금불초 꽃",
        "efficacy": "소담행수, 강기지구",
        "precautions": "음허노수, 진액부족 환자 주의. 포전(布煎) 필수(솜털 제거).",
    },
    {
        "name": "선퇴",
        "slug": "herbal-cicada-slough",
        "korean_name": "선퇴",
        "latin_name": "Cryptotympana pustulata Fabricius (탈피)",
        "category": "발한약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["폐", "간"]},
        "description": "소산풍열, 이인후, 투진, 퇴예명목, 식풍지경에 사용. 매미 허물",
        "efficacy": "소산풍열, 이인개음, 투진지양, 명목퇴예",
        "precautions": "임산부 주의. 특별한 약물 상호작용 보고 적음.",
    },
    # ── 해표약 보충 ──
    {
        "name": "생강",
        "slug": "herbal-fresh-ginger",
        "korean_name": "생강",
        "latin_name": "Zingiber officinale Roscoe (선)",
        "category": "해표약",
        "properties": {"taste": "신미", "nature": "미온", "meridian": ["폐", "비", "위"]},
        "description": "발한해표, 온중지구, 온폐지해에 사용. 생(生) 생강(건강과 구별)",
        "efficacy": "해표산한, 온중지구, 화담지해",
        "precautions": "음허내열, 열증 환자 과량 주의. 항응고제 병용 시 출혈 위험(진저롤의 항혈소판 작용).",
    },
    {
        "name": "총백",
        "slug": "herbal-allium-stalk",
        "korean_name": "총백",
        "latin_name": "Allium fistulosum L.",
        "category": "해표약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐", "위"]},
        "description": "발한해표, 산한통양에 사용. 파 흰줄기(뿌리 부근)",
        "efficacy": "발한해표, 산한통양",
        "precautions": "표허다한 환자 주의. 특별한 약물 상호작용 보고 적음.",
    },
]


async def seed_herbal_medicines_expanded(dry_run: bool = False) -> dict[str, int]:
    """한약재 확장 데이터 ~170종을 DB에 삽입한다."""
    stats = {"inserted": 0, "skipped": 0}

    async with async_session_factory() as session:
        for herb in HERBAL_MEDICINES_EXPANDED:
            if not dry_run:
                result = await session.execute(
                    text("""
                        INSERT INTO herbal_medicines (
                            name, slug, korean_name, latin_name,
                            category, properties, description,
                            efficacy, precautions
                        ) VALUES (
                            :name, :slug, :korean_name, :latin_name,
                            :category, CAST(:properties AS jsonb), :description,
                            :efficacy, :precautions
                        )
                        ON CONFLICT (slug) DO NOTHING
                        RETURNING id
                    """),
                    {
                        "name": herb["name"],
                        "slug": herb["slug"],
                        "korean_name": herb["korean_name"],
                        "latin_name": herb["latin_name"],
                        "category": herb["category"],
                        "properties": json.dumps(herb["properties"], ensure_ascii=False),
                        "description": herb["description"],
                        "efficacy": herb["efficacy"],
                        "precautions": herb["precautions"],
                    },
                )
                row = result.first()
                if row:
                    stats["inserted"] += 1
                else:
                    stats["skipped"] += 1
            else:
                stats["inserted"] += 1

        if not dry_run:
            await session.commit()

    return stats


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="한약재 확장 시드 데이터 적재")
    parser.add_argument("--dry-run", action="store_true", help="실제 DB 수정 없이 시뮬레이션")
    args = parser.parse_args()

    logger.info("한약재 확장 시드 데이터 적재 시작 (dry_run=%s)", args.dry_run)
    start = time.time()
    stats = asyncio.run(seed_herbal_medicines_expanded(dry_run=args.dry_run))
    elapsed = time.time() - start

    logger.info("=" * 60)
    logger.info("완료 (%.1f초) — 삽입: %d건, 건너뜀(중복): %d건",
                elapsed, stats["inserted"], stats["skipped"])
    logger.info("확장 한약재 데이터: %d종", len(HERBAL_MEDICINES_EXPANDED))
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
