"""한약재 시드 데이터 적재 스크립트.

대한약전 기반 주요 한약재 ~100종을 DB에 적재한다.
카테고리: 보기약, 보혈약, 보음약, 보양약, 해표약, 청열약, 거풍습약,
         이수삼습약, 활혈거어약, 지혈약, 안신약, 기타

사용법:
    python -m scripts.data-import.seed_herbal_medicines
    python -m scripts.data-import.seed_herbal_medicines --dry-run
"""

import asyncio
import json
import logging
import sys
import time
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sqlalchemy import text

from src.backend.core.database import async_session_factory

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)-7s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("seed_herbal_medicines")


# ============================================================
# 한약재 시드 데이터 (~100종)
# ============================================================

HERBAL_MEDICINES: list[dict[str, Any]] = [
    # ── 보기약 ──
    {
        "name": "인삼",
        "slug": "herbal-ginseng",
        "korean_name": "인삼",
        "latin_name": "Panax ginseng C.A.Mey.",
        "category": "보기약",
        "properties": {"taste": "감미", "nature": "미온", "meridian": ["비", "폐", "심"]},
        "description": "원기를 보하고 비폐의 기능을 돕는 대표적 보기약",
        "efficacy": "대보원기, 복맥고탈, 보비익폐, 생진양혈, 안신익지",
        "precautions": "고혈압, 불면, 열증 환자는 주의. 항응고제, 혈당강하제와 병용 시 주의 필요.",
    },
    {
        "name": "홍삼",
        "slug": "herbal-red-ginseng",
        "korean_name": "홍삼",
        "latin_name": "Panax ginseng C.A.Mey. (증삼)",
        "category": "보기약",
        "properties": {"taste": "감미, 미고미", "nature": "온", "meridian": ["비", "폐", "심"]},
        "description": "인삼을 증숙하여 온보 효능을 강화한 약재. 면역력 증진 및 피로 개선",
        "efficacy": "대보원기, 익기보혈, 강심, 항피로",
        "precautions": "열증, 고혈압 환자 주의. 항응고제, 당뇨약, 면역억제제와 병용 주의.",
    },
    {
        "name": "황기",
        "slug": "herbal-astragalus",
        "korean_name": "황기",
        "latin_name": "Astragalus membranaceus (Fisch.) Bge.",
        "category": "보기약",
        "properties": {"taste": "감미", "nature": "미온", "meridian": ["비", "폐"]},
        "description": "기를 보하고 체표를 견고하게 하며 이뇨, 배농에 사용하는 약재",
        "efficacy": "보기승양, 고표지한, 이수소종, 탁창배농",
        "precautions": "표실(表實) 또는 기체(氣滯)에는 사용 금지. 면역억제제와 병용 시 면역 반응 증가 주의.",
    },
    {
        "name": "백출",
        "slug": "herbal-atractylodes-white",
        "korean_name": "백출",
        "latin_name": "Atractylodes macrocephala Koidz.",
        "category": "보기약",
        "properties": {"taste": "감미, 고미", "nature": "온", "meridian": ["비", "위"]},
        "description": "비위를 건강하게 하고 습을 제거하는 약재",
        "efficacy": "건비익기, 조습이수, 지한, 안태",
        "precautions": "음허(陰虛)로 인한 내열에는 주의.",
    },
    {
        "name": "산약",
        "slug": "herbal-dioscorea",
        "korean_name": "산약",
        "latin_name": "Dioscorea batatas Decne.",
        "category": "보기약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["비", "폐", "신"]},
        "description": "비폐신 삼경을 보하는 약재. 마(참마)의 뿌리",
        "efficacy": "보비양위, 생진익폐, 보신삽정",
        "precautions": "습열(濕熱) 실사(實邪)에는 사용 금지.",
    },
    {
        "name": "대추",
        "slug": "herbal-jujube",
        "korean_name": "대추",
        "latin_name": "Ziziphus jujuba Mill.",
        "category": "보기약",
        "properties": {"taste": "감미", "nature": "온", "meridian": ["비", "위"]},
        "description": "비위를 보하고 기혈을 생성하며 약성을 조화시키는 약재",
        "efficacy": "보중익기, 양혈안신, 완화약성",
        "precautions": "습열, 담음(痰飮) 환자는 과량 복용 주의.",
    },
    {
        "name": "감초",
        "slug": "herbal-licorice",
        "korean_name": "감초",
        "latin_name": "Glycyrrhiza uralensis Fisch.",
        "category": "보기약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["심", "폐", "비", "위"]},
        "description": "백약의 왕으로 불리며 약성을 조화시키고 해독하는 대표적 약재",
        "efficacy": "보비익기, 윤폐지해, 완급지통, 조화제약, 청열해독",
        "precautions": "장기 복용 시 위알도스테론증(저칼륨혈증, 고혈압, 부종) 유발. 이뇨제, 항고혈압제, 강심배당체와 병용 금기.",
    },
    # ── 보혈약 ──
    {
        "name": "당귀",
        "slug": "herbal-angelica",
        "korean_name": "당귀",
        "latin_name": "Angelica gigas Nakai",
        "category": "보혈약",
        "properties": {"taste": "감미, 신미", "nature": "온", "meridian": ["심", "간", "비"]},
        "description": "혈을 보하고 활혈하며 통경지통에 사용하는 대표적 보혈약",
        "efficacy": "보혈활혈, 조경지통, 윤장통변",
        "precautions": "출혈 경향이 있는 환자 주의. 항응고제(와파린) 병용 시 출혈 위험 증가.",
    },
    {
        "name": "숙지황",
        "slug": "herbal-rehmannia-cooked",
        "korean_name": "숙지황",
        "latin_name": "Rehmannia glutinosa (Gaertn.) Libosch.",
        "category": "보혈약",
        "properties": {"taste": "감미", "nature": "미온", "meridian": ["간", "신"]},
        "description": "혈을 보하고 음을 자양하는 약재. 사물탕의 주약",
        "efficacy": "보혈자음, 보정익수",
        "precautions": "비위 허약, 소화불량 환자는 주의. 복부 팽만감 유발 가능.",
    },
    {
        "name": "백작약",
        "slug": "herbal-white-peony",
        "korean_name": "백작약",
        "latin_name": "Paeonia lactiflora Pall.",
        "category": "보혈약",
        "properties": {"taste": "고미, 산미", "nature": "미한", "meridian": ["간", "비"]},
        "description": "혈을 보하고 간기를 조절하며 통증을 완화하는 약재",
        "efficacy": "양혈유간, 완급지통, 렴음지한",
        "precautions": "항응고제와 병용 시 출혈 위험. 여로(藜蘆)와 배합 금기.",
    },
    {
        "name": "하수오",
        "slug": "herbal-polygonum",
        "korean_name": "하수오",
        "latin_name": "Polygonum multiflorum Thunb.",
        "category": "보혈약",
        "properties": {"taste": "고미, 감미, 삽미", "nature": "미온", "meridian": ["간", "신"]},
        "description": "간신을 보하고 정혈을 보익하며 백발을 흑발로 만드는 약재",
        "efficacy": "보간신, 익정혈, 오수발, 강근골",
        "precautions": "간독성 보고 사례 있음. 간질환 환자 주의. 장기 복용 시 간 기능 모니터링 필요.",
    },
    {
        "name": "아교",
        "slug": "herbal-donkey-hide-gelatin",
        "korean_name": "아교",
        "latin_name": "Equus asinus L. (교질)",
        "category": "보혈약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["폐", "간", "신"]},
        "description": "혈을 보하고 출혈을 멎게 하며 음을 자양하는 약재",
        "efficacy": "보혈, 지혈, 자음윤조",
        "precautions": "비위 허약으로 소화 장애가 있는 환자는 주의.",
    },
    # ── 보음약 ──
    {
        "name": "맥문동",
        "slug": "herbal-ophiopogon",
        "korean_name": "맥문동",
        "latin_name": "Ophiopogon japonicus (L.f.) Ker Gawl.",
        "category": "보음약",
        "properties": {"taste": "감미, 미고미", "nature": "미한", "meridian": ["심", "폐", "위"]},
        "description": "폐위의 음을 자양하고 진액을 생성하는 약재",
        "efficacy": "양음윤폐, 익위생진, 청심제번",
        "precautions": "비위 허한, 담음(痰飮) 환자는 주의.",
    },
    {
        "name": "구기자",
        "slug": "herbal-goji-berry",
        "korean_name": "구기자",
        "latin_name": "Lycium chinense Mill.",
        "category": "보음약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["간", "신", "폐"]},
        "description": "간신을 보하고 시력을 밝게 하는 약재. 식품으로도 활용",
        "efficacy": "자보간신, 명목, 윤폐",
        "precautions": "항응고제(와파린) 병용 시 INR 변동 보고. 혈당강하제와 저혈당 위험.",
    },
    {
        "name": "석곡",
        "slug": "herbal-dendrobium",
        "korean_name": "석곡",
        "latin_name": "Dendrobium nobile Lindl.",
        "category": "보음약",
        "properties": {"taste": "감미, 미한미", "nature": "미한", "meridian": ["위", "신"]},
        "description": "위음을 보하고 열을 내리며 진액을 생성하는 약재",
        "efficacy": "익위생진, 자음청열",
        "precautions": "온열병(溫熱病) 초기 또는 습온(濕溫) 환자는 주의.",
    },
    {
        "name": "여정자",
        "slug": "herbal-ligustrum",
        "korean_name": "여정자",
        "latin_name": "Ligustrum lucidum Ait.",
        "category": "보음약",
        "properties": {"taste": "감미, 고미", "nature": "평", "meridian": ["간", "신"]},
        "description": "간신의 음을 보하고 시력을 밝게 하는 약재",
        "efficacy": "자보간신, 명목, 오수발",
        "precautions": "비위 허한, 설사 환자는 주의.",
    },
    # ── 보양약 ──
    {
        "name": "녹용",
        "slug": "herbal-deer-antler",
        "korean_name": "녹용",
        "latin_name": "Cervus nippon Temminck",
        "category": "보양약",
        "properties": {"taste": "감미, 함미", "nature": "온", "meridian": ["간", "신"]},
        "description": "신양을 보하고 정혈을 보익하며 근골을 강하게 하는 약재",
        "efficacy": "보신양, 익정혈, 강근골, 조충임",
        "precautions": "음허화왕(陰虛火旺), 열증 환자 금기. 혈압 상승 가능.",
    },
    {
        "name": "음양곽",
        "slug": "herbal-epimedium",
        "korean_name": "음양곽",
        "latin_name": "Epimedium koreanum Nakai",
        "category": "보양약",
        "properties": {"taste": "신미, 감미", "nature": "온", "meridian": ["간", "신"]},
        "description": "신양을 보하고 근골을 강화하며 거풍습에 사용",
        "efficacy": "보신양, 강근골, 거풍습",
        "precautions": "음허화왕 환자 주의. 에스트로겐 유사 작용으로 호르몬 관련 약물 주의.",
    },
    {
        "name": "두충",
        "slug": "herbal-eucommia",
        "korean_name": "두충",
        "latin_name": "Eucommia ulmoides Oliv.",
        "category": "보양약",
        "properties": {"taste": "감미", "nature": "온", "meridian": ["간", "신"]},
        "description": "간신을 보하고 근골을 강화하며 안태에 사용하는 약재",
        "efficacy": "보간신, 강근골, 안태",
        "precautions": "음허화왕 환자는 주의. 혈압약과 병용 시 혈압 과도 저하 가능.",
    },
    {
        "name": "토사자",
        "slug": "herbal-cuscuta",
        "korean_name": "토사자",
        "latin_name": "Cuscuta chinensis Lam.",
        "category": "보양약",
        "properties": {"taste": "감미, 신미", "nature": "평", "meridian": ["간", "신"]},
        "description": "간신을 보하고 정을 고정하며 시력을 밝게 하는 약재",
        "efficacy": "보신익정, 양간명목, 지사안태",
        "precautions": "음허화왕, 대변조결(大便燥結) 환자는 주의.",
    },
    {
        "name": "육종용",
        "slug": "herbal-cistanche",
        "korean_name": "육종용",
        "latin_name": "Cistanche deserticola Ma",
        "category": "보양약",
        "properties": {"taste": "감미, 함미", "nature": "온", "meridian": ["신", "대장"]},
        "description": "신양을 보하고 정혈을 보익하며 윤장통변에 사용",
        "efficacy": "보신양, 익정혈, 윤장통변",
        "precautions": "음허화왕, 설사 환자 주의.",
    },
    # ── 해표약 ──
    {
        "name": "마황",
        "slug": "herbal-ephedra",
        "korean_name": "마황",
        "latin_name": "Ephedra sinica Stapf",
        "category": "해표약",
        "properties": {"taste": "신미, 미고미", "nature": "온", "meridian": ["폐", "방광"]},
        "description": "발한해표, 선폐평천, 이수소종에 사용하는 약재. 에페드린 함유",
        "efficacy": "발한해표, 선폐평천, 이수소종",
        "precautions": "심장질환, 고혈압, 갑상선기능항진증 환자 금기. MAO 억제제 병용 금기(고혈압 위기). 교감신경흥분제와 병용 금기.",
    },
    {
        "name": "계지",
        "slug": "herbal-cinnamon-twig",
        "korean_name": "계지",
        "latin_name": "Cinnamomum cassia (L.) J.Presl",
        "category": "해표약",
        "properties": {"taste": "신미, 감미", "nature": "온", "meridian": ["심", "폐", "방광"]},
        "description": "발한해표, 온경통맥에 사용. 계피나무 가지",
        "efficacy": "발한해기, 온경통맥, 통양화기",
        "precautions": "음허화왕, 열병, 임산부 주의. 쿠마린 함유로 항응고제 주의.",
    },
    {
        "name": "갈근",
        "slug": "herbal-pueraria",
        "korean_name": "갈근",
        "latin_name": "Pueraria lobata (Willd.) Ohwi",
        "category": "해표약",
        "properties": {"taste": "감미, 신미", "nature": "평", "meridian": ["비", "위"]},
        "description": "해기퇴열, 생진지갈에 사용. 칡뿌리",
        "efficacy": "해기퇴열, 생진지갈, 투진, 승양지사",
        "precautions": "이소플라본 함유로 에스트로겐 관련 약물과 상호작용 가능.",
    },
    {
        "name": "형개",
        "slug": "herbal-schizonepeta",
        "korean_name": "형개",
        "latin_name": "Schizonepeta tenuifolia (Benth.) Briq.",
        "category": "해표약",
        "properties": {"taste": "신미", "nature": "미온", "meridian": ["폐", "간"]},
        "description": "거풍해표, 지혈에 사용하는 약재",
        "efficacy": "거풍해표, 투진소창, 지혈",
        "precautions": "표허자한(表虛自汗) 환자는 주의.",
    },
    {
        "name": "방풍",
        "slug": "herbal-saposhnikovia",
        "korean_name": "방풍",
        "latin_name": "Saposhnikovia divaricata (Turcz.) Schischk.",
        "category": "해표약",
        "properties": {"taste": "신미, 감미", "nature": "미온", "meridian": ["방광", "간", "비"]},
        "description": "거풍해표, 승습지통, 지경에 사용하는 약재",
        "efficacy": "거풍해표, 승습지통, 지경",
        "precautions": "음허화왕, 혈허 발경 환자는 주의.",
    },
    {
        "name": "박하",
        "slug": "herbal-mentha",
        "korean_name": "박하",
        "latin_name": "Mentha arvensis L.",
        "category": "해표약",
        "properties": {"taste": "신미", "nature": "량", "meridian": ["폐", "간"]},
        "description": "소산풍열, 청두목리인, 투진에 사용",
        "efficacy": "소산풍열, 청두목, 이인후, 투진",
        "precautions": "자한, 음허발열 환자는 주의. 멘톨이 CYP3A4에 영향 가능.",
    },
    {
        "name": "시호",
        "slug": "herbal-bupleurum",
        "korean_name": "시호",
        "latin_name": "Bupleurum falcatum L.",
        "category": "해표약",
        "properties": {"taste": "고미, 신미", "nature": "미한", "meridian": ["간", "담"]},
        "description": "화해소양, 소간해울, 승양거함에 사용하는 약재",
        "efficacy": "화해퇴열, 소간해울, 승거양기",
        "precautions": "간독성 보고. 면역억제제(사이클로스포린) 병용 시 약효 감소 가능. 인터페론 유사 작용.",
    },
    # ── 청열약 ──
    {
        "name": "황금",
        "slug": "herbal-scutellaria",
        "korean_name": "황금",
        "latin_name": "Scutellaria baicalensis Georgi",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["폐", "담", "비", "대장", "소장"]},
        "description": "청열조습, 사화해독에 사용하는 대표적 청열약",
        "efficacy": "청열조습, 사화해독, 지혈, 안태",
        "precautions": "비위 허한 환자 주의. 바이칼린이 CYP 효소에 영향. 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "황련",
        "slug": "herbal-coptis",
        "korean_name": "황련",
        "latin_name": "Coptis chinensis Franch.",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["심", "비", "위", "간", "담", "대장"]},
        "description": "청열조습, 사화해독에 사용. 베르베린 함유",
        "efficacy": "청열조습, 사화해독",
        "precautions": "비위 허한 환자 금기. 베르베린이 CYP2D6, CYP3A4에 영향. 사이클로스포린 혈중 농도 증가 가능.",
    },
    {
        "name": "황백",
        "slug": "herbal-phellodendron",
        "korean_name": "황백",
        "latin_name": "Phellodendron amurense Rupr.",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["신", "방광", "대장"]},
        "description": "청열조습, 사화해독, 퇴허열에 사용",
        "efficacy": "청열조습, 사화제증, 퇴허열",
        "precautions": "비위 허한 환자 주의. 베르베린 함유.",
    },
    {
        "name": "치자",
        "slug": "herbal-gardenia",
        "korean_name": "치자",
        "latin_name": "Gardenia jasminoides J.Ellis",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["심", "폐", "삼초"]},
        "description": "사화제번, 청열이습, 양혈해독에 사용",
        "efficacy": "사화제번, 청열이습, 양혈해독, 소종지통",
        "precautions": "비위 허한, 설사 환자 금기.",
    },
    {
        "name": "금은화",
        "slug": "herbal-honeysuckle",
        "korean_name": "금은화",
        "latin_name": "Lonicera japonica Thunb.",
        "category": "청열약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["폐", "심", "위"]},
        "description": "청열해독, 소산풍열에 사용하는 약재",
        "efficacy": "청열해독, 소산풍열",
        "precautions": "비위 허한 환자 과량 복용 주의.",
    },
    {
        "name": "연교",
        "slug": "herbal-forsythia",
        "korean_name": "연교",
        "latin_name": "Forsythia suspensa (Thunb.) Vahl",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["폐", "심", "소장"]},
        "description": "청열해독, 소종산결에 사용. 금은화와 함께 사용 빈도 높음",
        "efficacy": "청열해독, 소종산결, 소산풍열",
        "precautions": "비위 허약, 기허(氣虛) 환자 주의.",
    },
    {
        "name": "대황",
        "slug": "herbal-rhubarb",
        "korean_name": "대황",
        "latin_name": "Rheum palmatum L.",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["비", "위", "대장", "간", "심포"]},
        "description": "사하공적, 청열사화, 양혈해독, 축어통경에 사용하는 약재",
        "efficacy": "사하공적, 청열사화, 양혈해독, 축어통경",
        "precautions": "임산부, 수유부 금기. 센노사이드 함유. 강심배당체(디곡신)와 병용 시 저칼륨혈증으로 디곡신 독성 증가.",
    },
    {
        "name": "생지황",
        "slug": "herbal-rehmannia-raw",
        "korean_name": "생지황",
        "latin_name": "Rehmannia glutinosa (Gaertn.) Libosch.",
        "category": "청열약",
        "properties": {"taste": "감미, 고미", "nature": "한", "meridian": ["심", "간", "신"]},
        "description": "청열양혈, 양음생진에 사용",
        "efficacy": "청열양혈, 양음생진",
        "precautions": "비위 허약, 설사 환자 주의. 소화 장애 유발 가능.",
    },
    # ── 거풍습약 ──
    {
        "name": "독활",
        "slug": "herbal-angelica-pubescens",
        "korean_name": "독활",
        "latin_name": "Angelica pubescens Maxim.",
        "category": "거풍습약",
        "properties": {"taste": "신미, 고미", "nature": "미온", "meridian": ["신", "방광"]},
        "description": "거풍습, 지통, 해표에 사용하는 약재",
        "efficacy": "거풍습, 지비통, 해표",
        "precautions": "음허내열 환자 주의.",
    },
    {
        "name": "강활",
        "slug": "herbal-ostericum",
        "korean_name": "강활",
        "latin_name": "Ostericum koreanum (Maxim.) Kitagawa",
        "category": "거풍습약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["방광", "신"]},
        "description": "거풍승습, 산한지통에 사용하는 약재",
        "efficacy": "거풍승습, 산한지통",
        "precautions": "혈허(血虛) 두통, 음허내열에는 사용 금지.",
    },
    {
        "name": "천마",
        "slug": "herbal-gastrodia",
        "korean_name": "천마",
        "latin_name": "Gastrodia elata Blume",
        "category": "거풍습약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["간"]},
        "description": "식풍지경, 평간잠양에 사용하는 약재. 두통, 현훈에 다용",
        "efficacy": "식풍지경, 평간잠양, 거풍통락",
        "precautions": "항경련제(발프로산, 카르바마제핀)와 병용 시 진정 효과 상승 가능. 진정제와 병용 주의.",
    },
    {
        "name": "위령선",
        "slug": "herbal-clematis",
        "korean_name": "위령선",
        "latin_name": "Clematis mandshurica Rupr.",
        "category": "거풍습약",
        "properties": {"taste": "신미, 함미", "nature": "온", "meridian": ["방광"]},
        "description": "거풍습, 통경락에 사용하는 약재",
        "efficacy": "거풍습, 통경락, 소골경",
        "precautions": "기혈 허약 환자는 주의. 과량 시 위장 자극.",
    },
    {
        "name": "오가피",
        "slug": "herbal-acanthopanax",
        "korean_name": "오가피",
        "latin_name": "Acanthopanax sessiliflorus (Rupr. & Maxim.) Seem.",
        "category": "거풍습약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["간", "신"]},
        "description": "거풍습, 보간신, 강근골에 사용하는 약재",
        "efficacy": "거풍습, 보간신, 강근골",
        "precautions": "혈압약과 병용 시 혈압 과도 저하 가능. 면역 관련 약물 주의.",
    },
    # ── 이수삼습약 ──
    {
        "name": "복령",
        "slug": "herbal-poria",
        "korean_name": "복령",
        "latin_name": "Poria cocos (Schw.) Wolf",
        "category": "이수삼습약",
        "properties": {"taste": "감미, 담미", "nature": "평", "meridian": ["심", "폐", "비", "신"]},
        "description": "이수삼습, 건비, 영심안신에 사용하는 약재",
        "efficacy": "이수삼습, 건비녕심",
        "precautions": "특별한 약물 상호작용 보고 적음. 이뇨제와 병용 시 과도한 이뇨 주의.",
    },
    {
        "name": "택사",
        "slug": "herbal-alisma",
        "korean_name": "택사",
        "latin_name": "Alisma orientale (Sam.) Juzep.",
        "category": "이수삼습약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["신", "방광"]},
        "description": "이수삼습, 사열에 사용하는 약재",
        "efficacy": "이수삼습, 사열",
        "precautions": "신허정활(腎虛精滑) 환자 주의. 이뇨제와 병용 시 전해질 불균형 가능.",
    },
    {
        "name": "차전자",
        "slug": "herbal-plantago",
        "korean_name": "차전자",
        "latin_name": "Plantago asiatica L.",
        "category": "이수삼습약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["간", "신", "폐", "소장"]},
        "description": "이수통림, 삼습지사, 청간명목에 사용",
        "efficacy": "이수통림, 삼습지사, 청간명목, 청폐화담",
        "precautions": "약물 흡수 저해 가능(식이섬유 유사 작용). 다른 약물과 시간 간격 유지.",
    },
    {
        "name": "의이인",
        "slug": "herbal-coix",
        "korean_name": "의이인",
        "latin_name": "Coix lacryma-jobi L. var. ma-yuen Stapf",
        "category": "이수삼습약",
        "properties": {"taste": "감미, 담미", "nature": "미한", "meridian": ["비", "위", "폐"]},
        "description": "이수삼습, 건비지사, 배농소종에 사용. 율무",
        "efficacy": "이수삼습, 건비지사, 제비, 배농",
        "precautions": "임산부 주의(자궁 수축 가능). 혈당강하 작용으로 당뇨약 병용 시 저혈당 주의.",
    },
    # ── 활혈거어약 ──
    {
        "name": "단삼",
        "slug": "herbal-salvia",
        "korean_name": "단삼",
        "latin_name": "Salvia miltiorrhiza Bge.",
        "category": "활혈거어약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["심", "심포", "간"]},
        "description": "활혈거어, 양혈안신에 사용하는 약재. 심혈관 질환에 다용",
        "efficacy": "활혈거어, 통경지통, 청심제번, 양혈소옹",
        "precautions": "항응고제(와파린) 병용 시 출혈 위험 증가. 디곡신 혈중 농도 증가 가능.",
    },
    {
        "name": "천궁",
        "slug": "herbal-cnidium",
        "korean_name": "천궁",
        "latin_name": "Cnidium officinale Makino",
        "category": "활혈거어약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["간", "담", "심포"]},
        "description": "활혈행기, 거풍지통에 사용하는 약재. 두통의 요약",
        "efficacy": "활혈행기, 거풍지통",
        "precautions": "음허화왕, 월경과다 환자 주의. 항응고제 병용 시 출혈 위험.",
    },
    {
        "name": "도인",
        "slug": "herbal-peach-kernel",
        "korean_name": "도인",
        "latin_name": "Prunus persica (L.) Batsch",
        "category": "활혈거어약",
        "properties": {"taste": "고미, 감미", "nature": "평", "meridian": ["심", "간", "대장"]},
        "description": "활혈거어, 윤장통변에 사용하는 약재. 복숭아 씨",
        "efficacy": "활혈거어, 윤장통변",
        "precautions": "임산부 금기. 항응고제 병용 시 출혈 위험 증가. 아미그달린 함유(과량 시 독성).",
    },
    {
        "name": "홍화",
        "slug": "herbal-carthamus",
        "korean_name": "홍화",
        "latin_name": "Carthamus tinctorius L.",
        "category": "활혈거어약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["심", "간"]},
        "description": "활혈통경, 거어지통에 사용하는 약재",
        "efficacy": "활혈통경, 거어지통",
        "precautions": "임산부 금기. 항응고제(와파린, 아스피린) 병용 시 출혈 위험 증가.",
    },
    {
        "name": "적작약",
        "slug": "herbal-red-peony",
        "korean_name": "적작약",
        "latin_name": "Paeonia lactiflora Pall. (적작약)",
        "category": "활혈거어약",
        "properties": {"taste": "고미", "nature": "미한", "meridian": ["간"]},
        "description": "청열양혈, 산어지통에 사용하는 약재",
        "efficacy": "청열양혈, 산어지통",
        "precautions": "항응고제 병용 시 출혈 위험. 여로(藜蘆)와 배합 금기.",
    },
    {
        "name": "삼칠",
        "slug": "herbal-notoginseng",
        "korean_name": "삼칠",
        "latin_name": "Panax notoginseng (Burkill) F.H.Chen",
        "category": "활혈거어약",
        "properties": {"taste": "감미, 미고미", "nature": "온", "meridian": ["간", "위"]},
        "description": "산어지혈, 소종정통에 사용하는 약재. 지혈과 활혈을 겸함",
        "efficacy": "산어지혈, 소종정통",
        "precautions": "임산부 주의. 항응고제, 항혈소판제 병용 시 출혈 위험.",
    },
    # ── 지혈약 ──
    {
        "name": "삼칠근",
        "slug": "herbal-notoginseng-root",
        "korean_name": "삼칠근",
        "latin_name": "Panax notoginseng (Burkill) F.H.Chen (근)",
        "category": "지혈약",
        "properties": {"taste": "감미, 미고미", "nature": "온", "meridian": ["간", "위"]},
        "description": "화어지혈, 활혈정통에 사용. 지혈의 성약",
        "efficacy": "화어지혈, 활혈정통",
        "precautions": "항응고제 병용 시 상호작용 가능(지혈 + 항응고 효과 상충).",
    },
    {
        "name": "지유",
        "slug": "herbal-sanguisorba",
        "korean_name": "지유",
        "latin_name": "Sanguisorba officinalis L.",
        "category": "지혈약",
        "properties": {"taste": "고미, 산미", "nature": "미한", "meridian": ["간", "대장"]},
        "description": "양혈지혈, 해독렴창에 사용",
        "efficacy": "양혈지혈, 해독렴창",
        "precautions": "탄닌 함유로 철분 흡수 저해 가능.",
    },
    {
        "name": "애엽",
        "slug": "herbal-artemisia",
        "korean_name": "애엽",
        "latin_name": "Artemisia argyi Lévl. et Vant.",
        "category": "지혈약",
        "properties": {"taste": "고미, 신미", "nature": "온", "meridian": ["간", "비", "신"]},
        "description": "온경지혈, 산한지통, 안태에 사용. 쑥",
        "efficacy": "온경지혈, 산한지통, 거습지양",
        "precautions": "음허혈열(陰虛血熱) 환자 주의. 항응고제 병용 시 지혈 효과 상충.",
    },
    # ── 안신약 ──
    {
        "name": "산조인",
        "slug": "herbal-ziziphus-seed",
        "korean_name": "산조인",
        "latin_name": "Ziziphus jujuba Mill. var. spinosa (Bunge) Hu ex H.F.Chow",
        "category": "안신약",
        "properties": {"taste": "감미, 산미", "nature": "평", "meridian": ["심", "비", "간", "담"]},
        "description": "양심안신, 렴한에 사용하는 대표적 안신약. 불면에 다용",
        "efficacy": "양심안신, 익음렴한",
        "precautions": "진정제, 수면제와 병용 시 과도한 진정 효과 주의.",
    },
    {
        "name": "원지",
        "slug": "herbal-polygala",
        "korean_name": "원지",
        "latin_name": "Polygala tenuifolia Willd.",
        "category": "안신약",
        "properties": {"taste": "고미, 신미", "nature": "온", "meridian": ["심", "신", "폐"]},
        "description": "안신익지, 거담개규에 사용하는 약재",
        "efficacy": "안신익지, 교통심신, 거담, 소옹",
        "precautions": "위궤양, 위염 환자 주의(위장 자극). 진정제와 상호작용 가능.",
    },
    {
        "name": "백자인",
        "slug": "herbal-biota-seed",
        "korean_name": "백자인",
        "latin_name": "Platycladus orientalis (L.) Franco",
        "category": "안신약",
        "properties": {"taste": "감미", "nature": "평", "meridian": ["심", "신", "대장"]},
        "description": "양심안신, 윤장통변에 사용하는 약재",
        "efficacy": "양심안신, 윤장통변",
        "precautions": "설사, 다담(多痰) 환자 주의.",
    },
    # ── 은행잎 ──
    {
        "name": "은행잎",
        "slug": "herbal-ginkgo",
        "korean_name": "은행잎",
        "latin_name": "Ginkgo biloba L.",
        "category": "활혈거어약",
        "properties": {"taste": "고미, 삽미", "nature": "평", "meridian": ["심", "폐"]},
        "description": "활혈화어, 통락지통에 사용. 뇌혈류 개선에 다용",
        "efficacy": "활혈화어, 통락지통, 렴폐평천",
        "precautions": "항응고제(와파린), 항혈소판제(아스피린) 병용 시 출혈 위험 증가. 수술 2주 전 중단.",
    },
    # ── 기타 주요 한약재 ──
    {
        "name": "오미자",
        "slug": "herbal-schisandra",
        "korean_name": "오미자",
        "latin_name": "Schisandra chinensis (Turcz.) Baill.",
        "category": "기타",
        "properties": {"taste": "산미", "nature": "온", "meridian": ["폐", "심", "신"]},
        "description": "렴폐자신, 생진렴한, 삽정지사에 사용. 다섯 가지 맛을 가진 약재",
        "efficacy": "렴폐지해, 자신삽정, 생진지갈, 수렴고탈",
        "precautions": "CYP3A4 억제 작용으로 CYP3A4 기질 약물(사이클로스포린, 타크로리무스 등)의 혈중 농도 증가 가능.",
    },
    {
        "name": "진피",
        "slug": "herbal-citrus-peel",
        "korean_name": "진피",
        "latin_name": "Citrus reticulata Blanco",
        "category": "기타",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["비", "폐"]},
        "description": "이기건비, 조습화담에 사용하는 약재. 귤껍질",
        "efficacy": "이기건비, 조습화담",
        "precautions": "감귤류 성분으로 CYP 효소에 영향 가능. 일부 약물과 상호작용 주의.",
    },
    {
        "name": "반하",
        "slug": "herbal-pinellia",
        "korean_name": "반하",
        "latin_name": "Pinellia ternata (Thunb.) Makino",
        "category": "기타",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["비", "위", "폐"]},
        "description": "조습화담, 강역지구에 사용하는 약재. 독성이 있어 법제 필수",
        "efficacy": "조습화담, 강역지구, 소비산결",
        "precautions": "임산부 금기. 독성 있어 생용 불가(법제 필수). 소화효소제와 상호작용 가능. 오두(烏頭)와 배합 금기.",
    },
    {
        "name": "지황",
        "slug": "herbal-rehmannia",
        "korean_name": "지황",
        "latin_name": "Rehmannia glutinosa (Gaertn.) Libosch.",
        "category": "보음약",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["심", "간", "신"]},
        "description": "자음보혈, 청열양혈에 사용. 육미지황환의 주약",
        "efficacy": "자음보혈, 청열양혈",
        "precautions": "비위 허약, 설사 환자 주의. 소화 장애 유발 가능.",
    },
    {
        "name": "현삼",
        "slug": "herbal-scrophularia",
        "korean_name": "현삼",
        "latin_name": "Scrophularia buergeriana Miq.",
        "category": "청열약",
        "properties": {"taste": "고미, 감미, 함미", "nature": "미한", "meridian": ["폐", "위", "신"]},
        "description": "양음강화, 해독산결에 사용하는 약재",
        "efficacy": "양음강화, 해독, 산결",
        "precautions": "비위 허한, 설사 환자 주의. 여로(藜蘆)와 배합 금기.",
    },
    {
        "name": "사삼",
        "slug": "herbal-adenophora",
        "korean_name": "사삼",
        "latin_name": "Adenophora triphylla (Thunb.) A.DC.",
        "category": "보음약",
        "properties": {"taste": "감미, 미고미", "nature": "미한", "meridian": ["폐", "위"]},
        "description": "양음청폐, 익위생진에 사용하는 약재",
        "efficacy": "양음청폐, 익위생진",
        "precautions": "여로(藜蘆)와 배합 금기. 풍한(風寒) 해수에는 부적합.",
    },
    {
        "name": "목향",
        "slug": "herbal-saussurea",
        "korean_name": "목향",
        "latin_name": "Saussurea costus (Falc.) Lipsch.",
        "category": "기타",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["비", "위", "대장", "삼초", "담"]},
        "description": "행기지통, 건비소식에 사용하는 약재",
        "efficacy": "행기지통, 건비소식",
        "precautions": "음허화왕, 진액부족 환자 주의.",
    },
    {
        "name": "향부자",
        "slug": "herbal-cyperus",
        "korean_name": "향부자",
        "latin_name": "Cyperus rotundus L.",
        "category": "기타",
        "properties": {"taste": "신미, 미고미, 미감미", "nature": "평", "meridian": ["간", "비", "삼초"]},
        "description": "소간이기, 조경지통에 사용. 여성 질환의 요약",
        "efficacy": "소간해울, 이기관중, 조경지통",
        "precautions": "기허무울(氣虛無鬱), 음허혈열 환자 주의.",
    },
    {
        "name": "사인",
        "slug": "herbal-amomum",
        "korean_name": "사인",
        "latin_name": "Amomum villosum Lour.",
        "category": "기타",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["비", "위", "신"]},
        "description": "화습행기, 온중지사, 안태에 사용하는 약재",
        "efficacy": "화습행기, 온중지사, 안태",
        "precautions": "음허혈조(陰虛血燥) 환자 주의.",
    },
    {
        "name": "건강",
        "slug": "herbal-dried-ginger",
        "korean_name": "건강",
        "latin_name": "Zingiber officinale Roscoe",
        "category": "기타",
        "properties": {"taste": "신미", "nature": "열", "meridian": ["비", "위", "심", "폐"]},
        "description": "온중산한, 회양통맥, 온폐화음에 사용. 건조 생강",
        "efficacy": "온중산한, 회양통맥, 온폐화음",
        "precautions": "음허내열, 혈열 환자 금기. 항응고제 병용 시 출혈 위험(항혈소판 작용).",
    },
    {
        "name": "부자",
        "slug": "herbal-aconite",
        "korean_name": "부자",
        "latin_name": "Aconitum carmichaeli Debeaux",
        "category": "기타",
        "properties": {"taste": "신미, 감미", "nature": "대열", "meridian": ["심", "신", "비"]},
        "description": "회양구역, 보화조양, 산한지통에 사용. 독성이 강하여 법제 필수",
        "efficacy": "회양구역, 보화조양, 산한지통",
        "precautions": "독성 극강(아코니틴). 법제 필수. 반하, 과루, 패모, 백렴, 백급과 배합 금기(십팔반). 임산부 금기.",
    },
    {
        "name": "오수유",
        "slug": "herbal-evodia",
        "korean_name": "오수유",
        "latin_name": "Evodia rutaecarpa (Juss.) Benth.",
        "category": "기타",
        "properties": {"taste": "신미, 고미", "nature": "열", "meridian": ["간", "비", "위", "신"]},
        "description": "산한지통, 강역지구, 조습에 사용하는 약재",
        "efficacy": "산한지통, 강역지구, 조습지사",
        "precautions": "음허화왕 환자 금기. CYP 효소에 영향 가능.",
    },
    {
        "name": "포공영",
        "slug": "herbal-taraxacum",
        "korean_name": "포공영",
        "latin_name": "Taraxacum platycarpum Dahlst.",
        "category": "청열약",
        "properties": {"taste": "고미, 감미", "nature": "한", "meridian": ["간", "위"]},
        "description": "청열해독, 소옹산결, 이습통림에 사용. 민들레",
        "efficacy": "청열해독, 소옹산결, 이습통림",
        "precautions": "비위 허한 환자 과량 복용 주의. 이뇨 작용으로 리튬 농도 변동 가능.",
    },
    {
        "name": "백지",
        "slug": "herbal-angelica-dahurica",
        "korean_name": "백지",
        "latin_name": "Angelica dahurica (Fisch.) Benth. et Hook.",
        "category": "해표약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐", "위"]},
        "description": "거풍해표, 지통, 통비규, 조습지대에 사용",
        "efficacy": "거풍해표, 지통, 통비규, 소종배농",
        "precautions": "음허화왕 환자 주의. 푸라노쿠마린 함유로 광과민 반응 가능.",
    },
    {
        "name": "목통",
        "slug": "herbal-akebia",
        "korean_name": "목통",
        "latin_name": "Akebia quinata (Houtt.) Decne.",
        "category": "이수삼습약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["심", "소장", "방광"]},
        "description": "이뇨통림, 통경하유에 사용하는 약재",
        "efficacy": "이뇨통림, 통경하유",
        "precautions": "임산부 금기. 신독성 보고(관목통 혼용 주의). 이뇨제와 병용 시 전해질 불균형.",
    },
    {
        "name": "용담",
        "slug": "herbal-gentiana",
        "korean_name": "용담",
        "latin_name": "Gentiana scabra Bge.",
        "category": "청열약",
        "properties": {"taste": "고미", "nature": "한", "meridian": ["간", "담"]},
        "description": "청열조습, 사간담화에 사용하는 약재",
        "efficacy": "청열조습, 사간담화",
        "precautions": "비위 허한 환자 주의. 장기 복용 시 위장 장애.",
    },
    {
        "name": "상백피",
        "slug": "herbal-morus-bark",
        "korean_name": "상백피",
        "latin_name": "Morus alba L.",
        "category": "기타",
        "properties": {"taste": "감미", "nature": "한", "meridian": ["폐"]},
        "description": "사폐평천, 이수소종에 사용. 뽕나무 뿌리껍질",
        "efficacy": "사폐평천, 이수소종",
        "precautions": "폐한(肺寒) 해수에는 부적합. 혈당강하 작용으로 당뇨약 병용 시 주의.",
    },
    {
        "name": "행인",
        "slug": "herbal-apricot-kernel",
        "korean_name": "행인",
        "latin_name": "Prunus armeniaca L.",
        "category": "기타",
        "properties": {"taste": "고미", "nature": "미온", "meridian": ["폐", "대장"]},
        "description": "지해평천, 윤장통변에 사용. 살구씨",
        "efficacy": "지해평천, 윤장통변",
        "precautions": "아미그달린 함유(과량 시 시안화물 중독 위험). 영유아 주의.",
    },
    {
        "name": "지모",
        "slug": "herbal-anemarrhena",
        "korean_name": "지모",
        "latin_name": "Anemarrhena asphodeloides Bge.",
        "category": "청열약",
        "properties": {"taste": "고미, 감미", "nature": "한", "meridian": ["폐", "위", "신"]},
        "description": "청열사화, 자음윤조에 사용하는 약재",
        "efficacy": "청열사화, 생진윤조",
        "precautions": "비위 허한, 설사 환자 주의. 혈당강하 작용 보고.",
    },
    {
        "name": "과루인",
        "slug": "herbal-trichosanthes-seed",
        "korean_name": "과루인",
        "latin_name": "Trichosanthes kirilowii Maxim.",
        "category": "기타",
        "properties": {"taste": "감미, 고미", "nature": "한", "meridian": ["폐", "위", "대장"]},
        "description": "윤폐화담, 이기관흉, 윤장통변에 사용",
        "efficacy": "윤폐화담, 이기관흉, 윤장통변",
        "precautions": "비위 허한, 설사 환자 주의. 오두(烏頭)와 배합 금기(십팔반).",
    },
    {
        "name": "패모",
        "slug": "herbal-fritillaria",
        "korean_name": "패모",
        "latin_name": "Fritillaria cirrhosa D.Don",
        "category": "기타",
        "properties": {"taste": "고미, 감미", "nature": "미한", "meridian": ["폐", "심"]},
        "description": "청열화담, 윤폐지해, 산결소옹에 사용하는 약재",
        "efficacy": "청화열담, 윤폐지해, 산결소옹",
        "precautions": "오두(烏頭)와 배합 금기(십팔반). 비위 허한 환자 주의.",
    },
    {
        "name": "길경",
        "slug": "herbal-platycodon",
        "korean_name": "길경",
        "latin_name": "Platycodon grandiflorus (Jacq.) A.DC.",
        "category": "기타",
        "properties": {"taste": "고미, 신미", "nature": "평", "meridian": ["폐"]},
        "description": "선폐거담, 이인배농에 사용하는 약재. 도라지",
        "efficacy": "선폐, 이인, 거담, 배농",
        "precautions": "음허구해, 토혈 환자 주의.",
    },
    {
        "name": "백합",
        "slug": "herbal-lily-bulb",
        "korean_name": "백합",
        "latin_name": "Lilium lancifolium Thunb.",
        "category": "보음약",
        "properties": {"taste": "감미", "nature": "미한", "meridian": ["심", "폐"]},
        "description": "윤폐지해, 청심안신에 사용. 나리 뿌리",
        "efficacy": "윤폐지해, 청심안신",
        "precautions": "풍한(風寒) 해수, 중한(中寒) 환자 주의.",
    },
    {
        "name": "오약",
        "slug": "herbal-lindera",
        "korean_name": "오약",
        "latin_name": "Lindera aggregata (Sims) Kosterm.",
        "category": "기타",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐", "비", "신", "방광"]},
        "description": "순기지통, 온신산한에 사용하는 약재",
        "efficacy": "순기지통, 온신산한",
        "precautions": "기허, 내열 환자 주의.",
    },
    {
        "name": "소엽",
        "slug": "herbal-perilla",
        "korean_name": "소엽",
        "latin_name": "Perilla frutescens (L.) Britt.",
        "category": "해표약",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["폐", "비"]},
        "description": "해표산한, 행기관중, 해어독에 사용. 차조기잎/들깻잎",
        "efficacy": "해표산한, 행기관중, 해어독",
        "precautions": "기허, 표허(表虛) 환자 주의.",
    },
    {
        "name": "초과",
        "slug": "herbal-tsaoko",
        "korean_name": "초과",
        "latin_name": "Amomum tsaoko Crevost et Lemaire",
        "category": "기타",
        "properties": {"taste": "신미", "nature": "온", "meridian": ["비", "위"]},
        "description": "조습온중, 제장절학에 사용하는 약재",
        "efficacy": "조습온중, 제장절학",
        "precautions": "기허혈조(氣虛血燥) 환자 주의.",
    },
    {
        "name": "석창포",
        "slug": "herbal-acorus",
        "korean_name": "석창포",
        "latin_name": "Acorus gramineus Soland.",
        "category": "안신약",
        "properties": {"taste": "신미, 고미", "nature": "온", "meridian": ["심", "위"]},
        "description": "개규화담, 개위, 예지안신에 사용하는 약재",
        "efficacy": "개규화담, 제습개위, 예지안신",
        "precautions": "음허양항(陰虛陽亢), 토혈, 활정(滑精) 환자 주의.",
    },
    {
        "name": "용안육",
        "slug": "herbal-longan",
        "korean_name": "용안육",
        "latin_name": "Dimocarpus longan Lour.",
        "category": "보혈약",
        "properties": {"taste": "감미", "nature": "온", "meridian": ["심", "비"]},
        "description": "보익심비, 양혈안신에 사용하는 약재",
        "efficacy": "보익심비, 양혈안신",
        "precautions": "담화(痰火), 습체(濕滯) 환자 주의.",
    },
]


async def seed_herbal_medicines(dry_run: bool = False) -> dict[str, int]:
    """한약재 ~100종을 DB에 삽입한다."""
    stats = {"inserted": 0, "skipped": 0}

    async with async_session_factory() as session:
        for herb in HERBAL_MEDICINES:
            if not dry_run:
                result = await session.execute(
                    text("""
                        INSERT INTO herbal_medicines (
                            name, slug, korean_name, latin_name,
                            category, properties, description,
                            efficacy, precautions
                        ) VALUES (
                            :name, :slug, :korean_name, :latin_name,
                            :category, CAST(:properties AS jsonb), :description,
                            :efficacy, :precautions
                        )
                        ON CONFLICT (slug) DO NOTHING
                        RETURNING id
                    """),
                    {
                        "name": herb["name"],
                        "slug": herb["slug"],
                        "korean_name": herb["korean_name"],
                        "latin_name": herb["latin_name"],
                        "category": herb["category"],
                        "properties": json.dumps(herb["properties"], ensure_ascii=False),
                        "description": herb["description"],
                        "efficacy": herb["efficacy"],
                        "precautions": herb["precautions"],
                    },
                )
                row = result.first()
                if row:
                    stats["inserted"] += 1
                else:
                    stats["skipped"] += 1
            else:
                stats["inserted"] += 1

        if not dry_run:
            await session.commit()

    return stats


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="한약재 시드 데이터 적재")
    parser.add_argument("--dry-run", action="store_true", help="실제 DB 수정 없이 시뮬레이션")
    args = parser.parse_args()

    logger.info("한약재 시드 데이터 적재 시작 (dry_run=%s)", args.dry_run)
    start = time.time()
    stats = asyncio.run(seed_herbal_medicines(dry_run=args.dry_run))
    elapsed = time.time() - start

    logger.info("=" * 60)
    logger.info("완료 (%.1f초) — 삽입: %d건, 건너뜀(중복): %d건",
                elapsed, stats["inserted"], stats["skipped"])
    logger.info("총 한약재 데이터: %d종", len(HERBAL_MEDICINES))
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
