#!/usr/bin/env bash
# ============================================================================
# Review Agent — 통합 품질 점수 계산
# 모든 check 스크립트를 실행하고 종합 점수/등급 산출
#
# 사용법:
#   ./check-quality.sh [project_dir]            # 점수 출력
#   ./check-quality.sh [project_dir] --report   # 마크다운 리포트 생성
# ============================================================================
set -euo pipefail

PROJECT_DIR="${1:-.}"
REPORT_MODE=false
[[ "${2:-}" == "--report" ]] && REPORT_MODE=true

REVIEW_DIR="${PROJECT_DIR}/scripts/review"
REPORT_DIR="${PROJECT_DIR}/.agents/ops-squad/qa-monitor/reports"
DATE=$(date '+%Y%m%d')
REPORT_FILE="${REPORT_DIR}/QUALITY-${DATE}.md"

# 점수 시스템
SCORE=100
TOTAL_ERRORS=0
TOTAL_WARNINGS=0
RESULTS=""

echo "=========================================="
echo "  Integrated Quality Score"
echo "  $(date '+%Y-%m-%d %H:%M')"
echo "=========================================="

# --- 개별 검사 실행 ---

run_check() {
    local name="$1" script="$2" args="${3:-}"
    local errors=0 warnings=0 output=""

    echo ""
    echo "▶ ${name}..."

    if [ ! -f "$script" ]; then
        echo "  SKIP: 스크립트 없음 (${script})"
        RESULTS="${RESULTS}| ${name} | SKIP | 0 | 0 |\n"
        return
    fi

    output=$(bash "$script" $args 2>&1) || true
    errors=$(echo "$output" | grep -c "FAIL:" || echo "0")
    warnings=$(echo "$output" | grep -c "WARN:" || echo "0")

    local status="PASS"
    if [ "$errors" -gt 0 ]; then
        status="FAIL"
    elif [ "$warnings" -gt 0 ]; then
        status="WARN"
    fi

    echo "  ${status}: 오류 ${errors}, 경고 ${warnings}"
    RESULTS="${RESULTS}| ${name} | ${status} | ${errors} | ${warnings} |\n"
    TOTAL_ERRORS=$((TOTAL_ERRORS + errors))
    TOTAL_WARNINGS=$((TOTAL_WARNINGS + warnings))
}

# 보안 검사
run_check "보안" "${REVIEW_DIR}/check-security.sh" "${PROJECT_DIR}/src/web"

# SEO 검사
run_check "SEO" "${REVIEW_DIR}/check-seo.sh" "${PROJECT_DIR}/src/web"

# 다크모드 검사
run_check "다크모드" "${REVIEW_DIR}/check-darkmode.sh" "${PROJECT_DIR}/src/web"

# 복잡도 검사
run_check "복잡도" "${REVIEW_DIR}/check-complexity.sh" "${PROJECT_DIR}/src/backend ${PROJECT_DIR}/src/web"

# API 호환성
run_check "API 호환성" "${REVIEW_DIR}/check-api-compat.sh" ""

# 코드 중복
run_check "코드 중복" "${REVIEW_DIR}/check-duplication.sh" "${PROJECT_DIR}/src/backend ${PROJECT_DIR}/src/web"

# --- 점수 계산 ---

# 감점 규칙
SECURITY_ERRORS=$(echo -e "$RESULTS" | grep "보안" | awk -F'|' '{print $4}' | xargs 2>/dev/null || echo "0")
API_ERRORS=$(echo -e "$RESULTS" | grep "API" | awk -F'|' '{print $4}' | xargs 2>/dev/null || echo "0")

# 보안/API 오류: -15점
SCORE=$((SCORE - (SECURITY_ERRORS + API_ERRORS) * 15))
# 기타 오류: -5점
OTHER_ERRORS=$((TOTAL_ERRORS - SECURITY_ERRORS - API_ERRORS))
SCORE=$((SCORE - OTHER_ERRORS * 5))
# 보안 경고: -3점
SCORE=$((SCORE - TOTAL_WARNINGS * 2))
# 바닥 0점
[ "$SCORE" -lt 0 ] && SCORE=0

# 등급 결정
GRADE="F"
if [ "$SCORE" -ge 90 ]; then GRADE="A"
elif [ "$SCORE" -ge 85 ]; then GRADE="A-"
elif [ "$SCORE" -ge 80 ]; then GRADE="B+"
elif [ "$SCORE" -ge 70 ]; then GRADE="B"
elif [ "$SCORE" -ge 60 ]; then GRADE="C"
elif [ "$SCORE" -ge 50 ]; then GRADE="D"
fi

echo ""
echo "=========================================="
echo "  품질 등급: ${GRADE} (${SCORE}점)"
echo "  오류: ${TOTAL_ERRORS}건, 경고: ${TOTAL_WARNINGS}건"
echo "=========================================="

# --- 이전 리포트 대비 변화 ---

PREV_REPORT=$(ls -t "${REPORT_DIR}"/QUALITY-*.md 2>/dev/null | head -1 || true)
PREV_SCORE=""
SCORE_CHANGE=""
if [ -n "$PREV_REPORT" ] && [ -f "$PREV_REPORT" ]; then
    PREV_SCORE=$(grep -oE '[0-9]+점' "$PREV_REPORT" | head -1 | tr -d '점' || echo "")
    if [ -n "$PREV_SCORE" ]; then
        DIFF=$((SCORE - PREV_SCORE))
        if [ "$DIFF" -gt 0 ]; then
            SCORE_CHANGE="+${DIFF} ↑"
        elif [ "$DIFF" -lt 0 ]; then
            SCORE_CHANGE="${DIFF} ↓"
        else
            SCORE_CHANGE="= (변동 없음)"
        fi
        echo "  이전 대비: ${SCORE_CHANGE}"
    fi
fi

# --- 리포트 생성 ---

if [ "$REPORT_MODE" = true ]; then
    mkdir -p "$REPORT_DIR"

    cat > "$REPORT_FILE" << EOF
# 코드 품질 리포트 — $(date '+%Y-%m-%d')

## 등급: ${GRADE} (${SCORE}점)
$([ -n "$SCORE_CHANGE" ] && echo "이전 대비: ${SCORE_CHANGE}" || true)

## 검사 결과

| 검사 | 상태 | 오류 | 경고 |
|------|------|------|------|
$(echo -e "$RESULTS")

## 요약

- **총 오류:** ${TOTAL_ERRORS}건
- **총 경고:** ${TOTAL_WARNINGS}건
- **검사 시각:** $(date '+%Y-%m-%d %H:%M KST')

## 점수 산정 기준

| 감점 항목 | 건수 | 감점 |
|-----------|------|------|
| 보안/API 오류 (-15점/건) | $((SECURITY_ERRORS + API_ERRORS)) | -$(( (SECURITY_ERRORS + API_ERRORS) * 15 ))점 |
| 기타 오류 (-5점/건) | ${OTHER_ERRORS} | -$((OTHER_ERRORS * 5))점 |
| 경고 (-2점/건) | ${TOTAL_WARNINGS} | -$((TOTAL_WARNINGS * 2))점 |

---
*Generated by Review Agent Quality System*
EOF

    echo ""
    echo "리포트 생성: ${REPORT_FILE}"
fi

# 오류가 있으면 비정상 종료
[ "$TOTAL_ERRORS" -gt 0 ] && exit 1
exit 0
